// Generated by yongol. Customize via manifest.yaml frontend.theme or DESIGN.md.
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: { DEFAULT: '#0f172a', foreground: '#f8fafc' },
        secondary: { DEFAULT: '#f1f5f9', foreground: '#0f172a' },
        accent: { DEFAULT: '#f1f5f9', foreground: '#0f172a' },
        destructive: { DEFAULT: '#ef4444', foreground: '#f8fafc' },
        muted: { DEFAULT: '#f1f5f9', foreground: '#64748b' },
        background: '#ffffff',
        foreground: '#0f172a',
        border: '#e2e8f0',
      },
      borderRadius: {
        lg: '0.75rem',
        md: '0.5rem',
        sm: '0.25rem',
      },
      spacing: {
        lg: '1.5rem',
        md: '1rem',
        sm: '0.5rem',
        xs: '0.25rem',
      },
    },
  },
  plugins: [],
}
