-- YONGOL_SCHEMA_HASH: 47ae5b9e1b2d52e6a1af0985ef63da0a1ff52a8612ee489f36ce9f5120ec8753
-- Generated by yongol dev at 2026-04-24T15:39:38Z

CREATE TABLE refresh_tokens (
    token_hash TEXT NOT NULL,
    claims JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (token_hash)
);
CREATE INDEX refresh_tokens_claims_idx ON refresh_tokens USING gin (claims);


CREATE TABLE users (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'member',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT users_role_check CHECK (role IN ('admin', 'member'))
);

INSERT INTO users (id, email, password_hash, role)
OVERRIDING SYSTEM VALUE
VALUES (0, 'nobody@system', '', 'member')
ON CONFLICT DO NOTHING;
CREATE UNIQUE INDEX users_email_key ON users (email);


CREATE TABLE workflows (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    owner_id BIGINT NOT NULL DEFAULT 0,
    title VARCHAR(255) NOT NULL,
    trigger_event VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT workflows_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT workflows_status_check CHECK (status IN ('draft', 'active', 'paused', 'archived'))
);

