//ff:func feature=gen-gogin type=generator control=sequence
//ff:what generateFFIgnore — filefunc validate 가 외부 도구 산출물(sqlc db.go 등)을 건너뛰도록 .ffignore 생성

package gogin

import (
	"os"
	"path/filepath"
)

// ffignoreContent lists paths that filefunc validate should skip.
// These are files generated by external tools (sqlc, oapi-codegen) whose
// internal structure cannot conform to filefunc rules (F1/F2/Q3).
const ffignoreContent = `# Auto-generated by yongol generate — do not edit manually.
# Regenerate with: yongol generate <specs> <arts>

# sqlc db.go: preserved multi-type/func core (DBTX + New + Queries + WithTx)
internal/db/db.go

# oapi-codegen RegisterHandlersWithOptions: route count drives line count
internal/api/register_handlers_with_options.gen.go
`

// generateFFIgnore writes backend/.ffignore so filefunc validate skips
// external tool output that cannot conform to filefunc structure rules.
func generateFFIgnore(artifactsDir string) error {
	dst := filepath.Join(artifactsDir, "backend", ".ffignore")
	return os.WriteFile(dst, []byte(ffignoreContent), 0o644)
}
