-- YONGOL_SCHEMA_HASH: 633c1f7b26034cdcb36267e9fbd25affdb1cce8401391586d17f52651a1eb662
-- Generated by yongol dev at 2026-04-24T11:28:27Z

CREATE TABLE execution_logs (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    workflow_id BIGINT NOT NULL DEFAULT 0,
    org_id BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'success',
    credits_spent BIGINT NOT NULL DEFAULT 0,
    executed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT execution_logs_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows (id),
    CONSTRAINT execution_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id)
);
CREATE INDEX execution_logs_org_id_idx ON execution_logs (org_id);
CREATE INDEX execution_logs_workflow_id_idx ON execution_logs (workflow_id);


CREATE TABLE organizations (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    plan_type VARCHAR(32) NOT NULL DEFAULT 'free',
    credits_balance BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT organizations_plan_type_check CHECK (plan_type IN ('free', 'pro', 'enterprise'))
);

INSERT INTO organizations (id, name, plan_type, credits_balance)
OVERRIDING SYSTEM VALUE
VALUES (0, 'system', 'free', 0)
ON CONFLICT DO NOTHING;


CREATE TABLE refresh_tokens (
    token_hash TEXT NOT NULL,
    claims JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (token_hash)
);
CREATE INDEX refresh_tokens_claims_idx ON refresh_tokens (claims);


CREATE TABLE users (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'member',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id),
    CONSTRAINT users_role_check CHECK (role IN ('admin', 'member'))
);

INSERT INTO users (id, org_id, email, password_hash, role)
OVERRIDING SYSTEM VALUE
VALUES (0, 0, 'nobody@system', '', 'member')
ON CONFLICT DO NOTHING;
CREATE UNIQUE INDEX users_email_key ON users (email);


CREATE TABLE workflows (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    title VARCHAR(255) NOT NULL,
    trigger_event VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT workflows_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id)
);

INSERT INTO workflows (id, org_id, title, trigger_event, status)
OVERRIDING SYSTEM VALUE
VALUES (0, 0, 'system', 'none', 'draft')
ON CONFLICT DO NOTHING;
CREATE INDEX workflows_org_id_idx ON workflows (org_id);

