// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=sequence
//ff:what ActivateWorkflow401JSONResponse.VisitActivateWorkflowResponse
//ff:checked llm=yongol-gen hash=8c6984a9
package api

import (
	"encoding/json"
	"net/http"
)

func (response ActivateWorkflow401JSONResponse) VisitActivateWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}
