// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what Action defines model for Action.
package api

// Action defines model for Action.
type Action struct {
	ActionType      *string `json:"action_type,omitempty"`
	Id              *int64  `json:"id,omitempty"`
	PayloadTemplate *string `json:"payload_template,omitempty"`
	SequenceOrder   *int64  `json:"sequence_order,omitempty"`
	WorkflowId      *int64  `json:"workflow_id,omitempty"`
}
