// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what AddActionJSONBody defines parameters for AddAction.
package api

// AddActionJSONBody defines parameters for AddAction.
type AddActionJSONBody struct {
	ActionType      string `json:"action_type"`
	PayloadTemplate string `json:"payload_template"`
	SequenceOrder   int64  `json:"sequence_order"`
}
