// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what AddActionJSONRequestBody defines body for AddAction for application/json ContentType.
package api

// AddActionJSONRequestBody defines body for AddAction for application/json ContentType.
type AddActionJSONRequestBody AddActionJSONBody
