// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=model control=sequence
//ff:what Defines values for UserRole.
package api

// Defines values for UserRole.
const (
	Admin  UserRole = "admin"
	Member UserRole = "member"
)

// Defines values for WorkflowStatus.
const (
	Active   WorkflowStatus = "active"
	Archived WorkflowStatus = "archived"
	Draft    WorkflowStatus = "draft"
	Paused   WorkflowStatus = "paused"
)
