// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what ErrorResponse defines model for ErrorResponse.
package api

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    *string                 `json:"code,omitempty"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Error   string                  `json:"error"`
}
