// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=sequence
//ff:what GetCurrentUser404JSONResponse.VisitGetCurrentUserResponse
//ff:checked llm=yongol-gen hash=cbb99059
package api

import (
	"encoding/json"
	"net/http"
)

func (response GetCurrentUser404JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}
