// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what MiddlewareFunc
package api

import (
	"github.com/gin-gonic/gin"
)

type MiddlewareFunc func(c *gin.Context)
