// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what Organization defines model for Organization.
package api

import (
	"time"
)

// Organization defines model for Organization.
type Organization struct {
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	CreditsBalance *int64     `json:"credits_balance,omitempty"`
	Id             *int64     `json:"id,omitempty"`
	Name           *string    `json:"name,omitempty"`
	PlanType       *string    `json:"plan_type,omitempty"`
}
