// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=sequence
//ff:what RegisterHandlersWithOptions creates http.Handler with additional options
//ff:checked llm=yongol-gen hash=212914dd
package api

import (
	"github.com/gin-gonic/gin"
)

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/signup", wrapper.Signup)
	router.GET(options.BaseURL+"/users/me", wrapper.GetCurrentUser)
	router.GET(options.BaseURL+"/workflows", wrapper.ListWorkflows)
	router.POST(options.BaseURL+"/workflows", wrapper.CreateWorkflow)
	router.POST(options.BaseURL+"/workflows/:id/actions", wrapper.AddAction)
	router.POST(options.BaseURL+"/workflows/:id/activate", wrapper.ActivateWorkflow)
	router.POST(options.BaseURL+"/workflows/:id/execute", wrapper.ExecuteWorkflow)
}
