// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what CreateWorkflow operation middleware
//ff:checked llm=yongol-gen hash=c78672d7
package api

import (
	"github.com/gin-gonic/gin"
)

// CreateWorkflow operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkflow(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateWorkflow(c)
}
