// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what ServerInterface represents all server handlers.
package api

import (
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	Login(c *gin.Context)

	// (POST /auth/register)
	Register(c *gin.Context)

	// (GET /workflows)
	ListWorkflows(c *gin.Context, params ListWorkflowsParams)

	// (POST /workflows)
	CreateWorkflow(c *gin.Context)

	// (POST /workflows/{id}/activate)
	ActivateWorkflow(c *gin.Context, id int64)
}
