// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=selection
//ff:what Valid indicates whether the value is a known member of the SignupJSONBodyPlanType enum.
//ff:checked llm=yongol-gen hash=f0e34850
package api

// Valid indicates whether the value is a known member of the SignupJSONBodyPlanType enum.
func (e SignupJSONBodyPlanType) Valid() bool {
	switch e {
	case Enterprise:
		return true
	case Free:
		return true
	case Pro:
		return true
	default:
		return false
	}
}
