// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what SignupJSONBody defines parameters for Signup.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// SignupJSONBody defines parameters for Signup.
type SignupJSONBody struct {
	CreditsBalance int64                  `json:"credits_balance"`
	Email          openapi_types.Email    `json:"email"`
	Name           string                 `json:"name"`
	OrgName        string                 `json:"org_name"`
	Password       string                 `json:"password"`
	PlanType       SignupJSONBodyPlanType `json:"plan_type"`
}
