// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what Signup200JSONResponse
package api

type Signup200JSONResponse struct {
	AccessToken  *string       `json:"access_token,omitempty"`
	Organization *Organization `json:"organization,omitempty"`
	User         *User         `json:"user,omitempty"`
}
