// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what AddAction operation middleware
//ff:checked llm=yongol-gen hash=9bbeb812
package api

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

// AddAction operation middleware
func (sh *strictHandler) AddAction(ctx *gin.Context, id int64) {
	var request AddActionRequestObject

	request.Id = id

	var body AddActionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddAction(ctx, request.(AddActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddAction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(AddActionResponseObject); ok {
		if err := validResponse.VisitAddActionResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
