// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what StrictServerInterface represents all server handlers.
package api

import (
	"context"
)

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (POST /auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)

	// (GET /users/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)

	// (GET /workflows)
	ListWorkflows(ctx context.Context, request ListWorkflowsRequestObject) (ListWorkflowsResponseObject, error)

	// (POST /workflows)
	CreateWorkflow(ctx context.Context, request CreateWorkflowRequestObject) (CreateWorkflowResponseObject, error)

	// (POST /workflows/{id}/actions)
	AddAction(ctx context.Context, request AddActionRequestObject) (AddActionResponseObject, error)

	// (POST /workflows/{id}/activate)
	ActivateWorkflow(ctx context.Context, request ActivateWorkflowRequestObject) (ActivateWorkflowResponseObject, error)

	// (POST /workflows/{id}/execute)
	ExecuteWorkflow(ctx context.Context, request ExecuteWorkflowRequestObject) (ExecuteWorkflowResponseObject, error)
}
