// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what Workflow defines model for Workflow.
package api

import (
	"time"
)

// Workflow defines model for Workflow.
type Workflow struct {
	CreatedAt    time.Time      `json:"created_at"`
	Id           int64          `json:"id"`
	OwnerId      int64          `json:"owner_id"`
	Status       WorkflowStatus `json:"status"`
	Title        string         `json:"title"`
	TriggerEvent string         `json:"trigger_event"`
}
