// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=selection
//ff:what Valid indicates whether the value is a known member of the WorkflowStatus enum.
//ff:checked llm=yongol-gen hash=693dfaa1
package api

// Valid indicates whether the value is a known member of the WorkflowStatus enum.
func (e WorkflowStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Archived:
		return true
	case Draft:
		return true
	case Paused:
		return true
	default:
		return false
	}
}
