// Generated by yongol. Canonical shadcn/ui cn() helper.
// Combines clsx (conditional classes) with tailwind-merge (conflict resolution).
import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
