//ff:func feature=gen-splitter type=test control=iteration dimension=1
//ff:what docOf / funcDoc / genDeclDoc / detectControl / controlFor / funcTypeFor / extractHeader

package splitter

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"
)

func parseDeclWithComments(t *testing.T, src string) ast.Decl {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "x.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	return f.Decls[0]
}

func TestFuncDoc(t *testing.T) {
	d := parseDeclWithComments(t, "package p\n// Foo does things.\nfunc Foo() {}").(*ast.FuncDecl)
	if got := funcDoc(d); got != "Foo does things.\n" {
		t.Errorf("funcDoc = %q", got)
	}
	nodoc := parseDeclWithComments(t, "package p\nfunc Bar() {}").(*ast.FuncDecl)
	if got := funcDoc(nodoc); got != "" {
		t.Errorf("no-doc funcDoc = %q, want empty", got)
	}
}

func TestGenDeclDoc(t *testing.T) {
	wrapped := parseDeclWithComments(t, "package p\n// Row is a row.\ntype Row struct{}").(*ast.GenDecl)
	if got := genDeclDoc(wrapped); got != "Row is a row.\n" {
		t.Errorf("wrapped doc = %q", got)
	}
	// doc on inner TypeSpec
	inner := parseDeclWithComments(t, "package p\ntype (\n// Inner doc.\nInner struct{}\n)").(*ast.GenDecl)
	if got := genDeclDoc(inner); got != "Inner doc.\n" {
		t.Errorf("inner spec doc = %q", got)
	}
	multi := parseDeclWithComments(t, "package p\ntype (\nA struct{}\nB struct{}\n)").(*ast.GenDecl)
	if got := genDeclDoc(multi); got != "" {
		t.Errorf("multi-spec doc = %q, want empty", got)
	}
}

func TestDocOf(t *testing.T) {
	fn := parseDeclWithComments(t, "package p\n// f doc.\nfunc f() {}")
	if got := docOf(fn); got != "f doc.\n" {
		t.Errorf("docOf func = %q", got)
	}
	gd := parseDeclWithComments(t, "package p\n// T doc.\ntype T int")
	if got := docOf(gd); got != "T doc.\n" {
		t.Errorf("docOf gendecl = %q", got)
	}
}

func TestDetectControl(t *testing.T) {
	cases := []struct {
		name    string
		body    string
		wantC   string
		wantDim string
	}{
		{"sequence", "x := 1\n_ = x", "sequence", ""},
		{"loop", "for i := 0; i < 3; i++ {}", "iteration", "1"},
		{"range", "for range []int{} {}", "iteration", "1"},
		{"switch", "switch {\ncase true:\n}", "selection", ""},
		{"both falls to sequence", "for {}\nswitch {\n}", "sequence", ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			fn := parseDeclWithComments(t, "package p\nfunc f() {\n"+c.body+"\n}").(*ast.FuncDecl)
			gotC, gotDim := detectControl(fn.Body)
			if gotC != c.wantC || gotDim != c.wantDim {
				t.Errorf("detectControl = (%q,%q), want (%q,%q)", gotC, gotDim, c.wantC, c.wantDim)
			}
		})
	}
	// nil body
	if c, d := detectControl(nil); c != "sequence" || d != "" {
		t.Errorf("nil body = (%q,%q)", c, d)
	}
}

func TestControlFor(t *testing.T) {
	fn := parseDeclWithComments(t, "package p\nfunc f() { for {} }")
	if c, d := controlFor(fn); c != "iteration" || d != "1" {
		t.Errorf("func loop = (%q,%q)", c, d)
	}
	gd := parseDeclWithComments(t, "package p\ntype T int")
	if c, d := controlFor(gd); c != "sequence" || d != "" {
		t.Errorf("gendecl = (%q,%q)", c, d)
	}
}

func TestFuncTypeFor(t *testing.T) {
	if got := funcTypeFor(ToolOAPICodegen); got != "handler" {
		t.Errorf("oapi = %q, want handler", got)
	}
	if got := funcTypeFor(ToolSQLC); got != "query" {
		t.Errorf("sqlc = %q, want query", got)
	}
	if got := funcTypeFor(Tool("x")); got != "util" {
		t.Errorf("default = %q, want util", got)
	}
}

func TestExtractHeader(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "g.go")
	content := "// Code generated by tool. DO NOT EDIT.\n//go:build x\n\npackage p\n"
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	got := extractHeader(p)
	want := "// Code generated by tool. DO NOT EDIT.\n//go:build x"
	if got != want {
		t.Errorf("extractHeader = %q, want %q", got, want)
	}
	// missing file -> empty
	if got := extractHeader(filepath.Join(dir, "nope.go")); got != "" {
		t.Errorf("missing file = %q, want empty", got)
	}
}
