//ff:func feature=gen-splitter type=test control=sequence
//ff:what docOf / funcDoc / genDeclDoc / detectControl / controlFor / funcTypeFor / extractHeader
package splitter

import (
	"os"
	"path/filepath"
	"testing"
)

func TestExtractHeader(t *testing.T) {
	dir := t.TempDir()
	p := filepath.Join(dir, "g.go")
	content := "// Code generated by tool. DO NOT EDIT.\n//go:build x\n\npackage p\n"
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	got := extractHeader(p)
	want := "// Code generated by tool. DO NOT EDIT.\n//go:build x"
	if got != want {
		t.Errorf("extractHeader = %q, want %q", got, want)
	}
	// missing file -> empty
	if got := extractHeader(filepath.Join(dir, "nope.go")); got != "" {
		t.Errorf("missing file = %q, want empty", got)
	}
}
