//ff:func feature=gen-splitter type=util control=iteration dimension=1
//ff:what extractHeader — 원본 파일 최상단의 "Code generated by ... DO NOT EDIT." 배너 라인 추출
package splitter

import (
	"bufio"
	"os"
	"strings"
)

// extractHeader reads srcPath line by line and returns the contiguous
// block of top-of-file comments starting from the first line, stopping
// at the first blank line or non-comment line. This captures the
// generator banner (and any //go:build directive) that must be replicated
// in every split file so downstream tools keep recognising the output.
func extractHeader(srcPath string) string {
	f, err := os.Open(srcPath)
	if err != nil {
		return ""
	}
	defer f.Close()
	var lines []string
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			break
		}
		if !strings.HasPrefix(trimmed, "//") {
			break
		}
		lines = append(lines, line)
	}
	return strings.Join(lines, "\n")
}
