//ff:func feature=gen-splitter type=util control=iteration dimension=1
//ff:what preserveComments — CommentMap 에서 선언 직전에 붙은 doc / directive 주석을 수집
package splitter

import "go/ast"

// preserveComments returns the comment groups that the CommentMap
// associates with decl. This captures the doc comment, //go:generate,
// //go:build and similar directives, so write_split_files.go can
// re-emit them alongside the injected //ff:func annotation without
// losing information that the original generator relied on.
//
// Leading /*! copyright-style */ banners that ast.CommentMap attaches to
// the file preamble are NOT included here — those stay with the original
// file (which is deleted) and are recreated by write_split_files.go as
// "Code generated by <tool>. DO NOT EDIT." headers.
func preserveComments(cmap ast.CommentMap, decl ast.Decl) []*ast.CommentGroup {
	var out []*ast.CommentGroup
	for _, grp := range cmap[decl] {
		if grp == nil {
			continue
		}
		out = append(out, grp)
	}
	return out
}
