//ff:type feature=gen-splitter type=model
//ff:what splitUnit — 동일 타깃 파일로 합쳐질 선언/imports/어노테이션 묶음
package splitter

import "go/ast"

// splitUnit is the intermediate representation for one output file.
// FileName is relative to outDir. PkgName matches the source file's
// package clause. Header is the "Code generated by ... DO NOT EDIT."
// banner copied verbatim from the original. Annotations holds the
// //ff:func or //ff:type + //ff:what lines (without leading "//").
// Decls is the ordered list of top-level declarations belonging to this
// file. Docs parallels Decls and keeps each decl's doc comment text for
// summary extraction. Imports is the subset of the source file's
// imports actually used by these decls.
type splitUnit struct {
	FileName    string
	PkgName     string
	Header      string
	Annotations []string
	Decls       []ast.Decl
	Docs        []string
	Imports     []*ast.ImportSpec
}
