//ff:func feature=gen-splitter type=test control=iteration dimension=1
//ff:what TestSplitFile_DuplicateImportPath — 동일 import path 에 aliased+unaliased 엔트리가 있을 때 중복 제거 검증

package splitter

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSplitFile_DuplicateImportPath(t *testing.T) {
	src := `// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgtype "github.com/jackc/pgx/v5/pgtype"
)

type ExecutionLog struct {
	CreatedAt pgtype.Timestamptz
}
`
	tmp := t.TempDir()
	srcPath := filepath.Join(tmp, "models.go")
	if err := os.WriteFile(srcPath, []byte(src), 0o644); err != nil {
		t.Fatalf("write src: %v", err)
	}
	outDir := filepath.Join(tmp, "out")
	written, err := SplitFile(srcPath, outDir, ToolSQLC)
	if err != nil {
		t.Fatalf("SplitFile: %v", err)
	}
	if len(written) == 0 {
		t.Fatal("expected at least 1 split file")
	}
	for _, name := range written {
		data, err := os.ReadFile(filepath.Join(outDir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		body := string(data)
		count := strings.Count(body, `"github.com/jackc/pgx/v5/pgtype"`)
		if count > 1 {
			t.Errorf("%s has %d pgtype import entries, want 1:\n%s", name, count, body)
		}
	}
}
