//ff:func feature=gen-splitter type=test control=iteration dimension=1
//ff:what TestSplitFile_OAPISample — oapi-codegen 스타일 fixture 를 분할해 func/type/const 분리 검증
package splitter

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSplitFile_OAPISample(t *testing.T) {
	src := `// Package api — fixture.
// Code generated by oapi-codegen DO NOT EDIT.
package api

import (
	"fmt"
	"strings"
)

const (
	Asc  SortDir = "asc"
	Desc SortDir = "desc"
)

type SortDir string

type User struct {
	Name string
}

func (u User) Greet() string {
	return fmt.Sprintf("hi %s", strings.ToUpper(u.Name))
}

func ListUsers() []User {
	out := []User{}
	for i := 0; i < 3; i++ {
		out = append(out, User{Name: "u"})
	}
	return out
}
`
	tmp := t.TempDir()
	srcPath := filepath.Join(tmp, "server.gen.go")
	if err := os.WriteFile(srcPath, []byte(src), 0o644); err != nil {
		t.Fatalf("write src: %v", err)
	}
	outDir := filepath.Join(tmp, "out")
	written, err := SplitFile(srcPath, outDir, ToolOAPICodegen)
	if err != nil {
		t.Fatalf("SplitFile: %v", err)
	}
	if len(written) < 4 {
		t.Fatalf("expected >=4 split files, got %d: %v", len(written), written)
	}
	mustExist := []string{
		"sort_dir.gen.go",
		"user.gen.go",
		"user_greet.gen.go",
		"list_users.gen.go",
	}
	for _, name := range mustExist {
		data, err := os.ReadFile(filepath.Join(outDir, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		body := string(data)
		if !strings.Contains(body, "package api") {
			t.Errorf("%s missing package clause", name)
		}
		if !strings.Contains(body, "//ff:") {
			t.Errorf("%s missing ff annotation", name)
		}
	}
	greet, _ := os.ReadFile(filepath.Join(outDir, "user_greet.gen.go"))
	if !strings.Contains(string(greet), `"fmt"`) || !strings.Contains(string(greet), `"strings"`) {
		t.Errorf("user_greet.gen.go should keep fmt+strings imports, got:\n%s", string(greet))
	}
	list, _ := os.ReadFile(filepath.Join(outDir, "list_users.gen.go"))
	if strings.Contains(string(list), `"strings"`) {
		t.Errorf("list_users.gen.go should drop unused strings import")
	}
	if !strings.Contains(string(list), "control=iteration") {
		t.Errorf("list_users.gen.go should be tagged iteration (has for loop), got:\n%s", string(list))
	}
}
