//ff:func feature=gen-splitter type=util control=iteration dimension=1
//ff:what writeSplitUnit — 1 unit(선언 묶음) 을 헤더/어노테이션/imports/본문 순으로 조립해 파일로 기록
package splitter

import (
	"bytes"
	"fmt"
	"go/format"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/park-jun-woo/yongol/pkg/generate/ffhash"
)

// writeSplitUnit renders a single SplitUnit (decls destined for the same
// target file) to outDir. The output layout is:
//
//  1. generator header ("// Code generated by ... DO NOT EDIT.")
//  2. //ff:func / //ff:type + //ff:what lines
//  3. package declaration
//  4. filtered import block (collectImportsForDecl result)
//  5. printed decl bodies (go/printer with the original FileSet)
//
// The combined bytes are passed through go/format.Source so gofmt handles
// indentation, import grouping and final newline. On success the file is
// written with 0o644 perms; parent directory is assumed to exist.
func writeSplitUnit(outDir string, fset *token.FileSet, unit *splitUnit) error {
	var buf bytes.Buffer
	writeHeaderBlock(&buf, unit.Header)
	writeAnnotationBlock(&buf, unit.Annotations)
	fmt.Fprintf(&buf, "package %s\n\n", unit.PkgName)
	writeImportBlock(&buf, unit.Imports)
	for _, decl := range unit.Decls {
		if err := printer.Fprint(&buf, fset, decl); err != nil {
			return fmt.Errorf("print decl: %w", err)
		}
		buf.WriteString("\n\n")
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		src = buf.Bytes()
	}
	if strings.HasSuffix(unit.FileName, ".go") {
		src = ffhash.InjectCheckedLine(src)
	}
	return os.WriteFile(filepath.Join(outDir, unit.FileName), src, 0o644)
}
