//ff:func feature=gen-splitter type=test control=sequence
//ff:what splitter 내부 함수 by-name 직접 호출 테스트 — tsma content-aware 귀속용
package splitter

import (
	"testing"
)

func TestWriteSplitUnit_ZeroCov(t *testing.T) {
	fset, f := bnParseFile(t, "package p\nimport \"fmt\"\nfunc Foo() { fmt.Println(1) }")
	dir := t.TempDir()
	u := &splitUnit{
		FileName:    "foo.go",
		PkgName:     "p",
		Header:      "// Code generated by yongol. DO NOT EDIT.",
		Annotations: []string{"ff:func feature=x type=handler control=sequence", "ff:what foo"},
		Decls:       f.Decls[1:],
		Imports:     f.Imports,
	}
	if err := writeSplitUnit(dir, fset, u); err != nil {
		t.Fatalf("writeSplitUnit: %v", err)
	}
}
