//ff:func feature=gen-splitter type=test control=sequence
//ff:what splitter 내부 함수 by-name 직접 호출 테스트 — tsma content-aware 귀속용

package splitter

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

func bnParseFile(t *testing.T, src string) (*token.FileSet, *ast.File) {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "x.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	return fset, f
}

func TestCollectImportsForDecl_ZeroCov(t *testing.T) {
	_, f := bnParseFile(t, "package p\nimport (\n\t\"fmt\"\n\t\"net/http\"\n)\nfunc f() { fmt.Println(1) }")
	out := collectImportsForDecl(f.Decls[1:], f.Imports)
	if len(out) != 1 || !strings.Contains(out[0].Path.Value, "fmt") {
		t.Errorf("expected only fmt import, got %#v", out)
	}
}

func TestRenderImportSpec_ZeroCov(t *testing.T) {
	plain := &ast.ImportSpec{Path: &ast.BasicLit{Value: `"fmt"`}}
	if got := renderImportSpec(plain); got != `"fmt"` {
		t.Errorf("plain=%q", got)
	}
	aliased := &ast.ImportSpec{Name: &ast.Ident{Name: "f"}, Path: &ast.BasicLit{Value: `"fmt"`}}
	if got := renderImportSpec(aliased); got != `f "fmt"` {
		t.Errorf("aliased=%q", got)
	}
}

func TestInjectFFAnnotation_ZeroCov(t *testing.T) {
	fn := firstDecl(t, "package p\n// Foo does X.\nfunc Foo() {}")
	lines := injectFFAnnotation(fn, "auth", "handler", "sequence", "", "Foo does X.")
	if len(lines) != 2 || !strings.HasPrefix(lines[0], "ff:func") {
		t.Errorf("func annotation wrong: %#v", lines)
	}
	td := firstDecl(t, "package p\ntype Bar struct{}")
	tlines := injectFFAnnotation(td, "auth", "model", "sequence", "", "")
	if !strings.HasPrefix(tlines[0], "ff:type") {
		t.Errorf("type annotation wrong: %#v", tlines)
	}
}

func TestFinaliseUnit_ZeroCov(t *testing.T) {
	_, f := bnParseFile(t, "package p\nimport \"fmt\"\nfunc Foo() { fmt.Println(1) }")
	u := &splitUnit{
		PkgName: "p",
		Decls:   f.Decls[1:],
		Docs:    []string{"Foo does X."},
	}
	finaliseUnit(u, "auth", "handler", nil, f.Imports)
	if len(u.Annotations) == 0 {
		t.Errorf("annotations not filled")
	}
}

func TestWriteAnnotationBlock_ZeroCov(t *testing.T) {
	var buf bytes.Buffer
	writeAnnotationBlock(&buf, []string{"ff:func feature=x", "ff:what y"})
	if !strings.Contains(buf.String(), "//ff:func") {
		t.Errorf("annotation block wrong: %q", buf.String())
	}
}

func TestWriteHeaderBlock_ZeroCov(t *testing.T) {
	var buf bytes.Buffer
	writeHeaderBlock(&buf, "// Code generated")
	if !strings.Contains(buf.String(), "Code generated") {
		t.Errorf("header missing: %q", buf.String())
	}
	var empty bytes.Buffer
	writeHeaderBlock(&empty, "")
	if empty.Len() != 0 {
		t.Errorf("empty header should be no-op")
	}
}

func TestWriteImportBlock_ZeroCov(t *testing.T) {
	var buf bytes.Buffer
	imps := []*ast.ImportSpec{{Path: &ast.BasicLit{Value: `"fmt"`}}}
	writeImportBlock(&buf, imps)
	if !strings.Contains(buf.String(), "import (") {
		t.Errorf("import block wrong: %q", buf.String())
	}
	var empty bytes.Buffer
	writeImportBlock(&empty, nil)
	if empty.Len() != 0 {
		t.Errorf("empty imports should be no-op")
	}
}

func TestWriteSplitUnit_ZeroCov(t *testing.T) {
	fset, f := bnParseFile(t, "package p\nimport \"fmt\"\nfunc Foo() { fmt.Println(1) }")
	dir := t.TempDir()
	u := &splitUnit{
		FileName:    "foo.go",
		PkgName:     "p",
		Header:      "// Code generated by yongol. DO NOT EDIT.",
		Annotations: []string{"ff:func feature=x type=handler control=sequence", "ff:what foo"},
		Decls:       f.Decls[1:],
		Imports:     f.Imports,
	}
	if err := writeSplitUnit(dir, fset, u); err != nil {
		t.Fatalf("writeSplitUnit: %v", err)
	}
}
