-- Generated by yongol dev at 2026-04-24T14:40:18Z
-- Changes:
--   * create table refresh_tokens
--   * create table users
--   * create table workflows
--   * insert sentinel users
--   * add check users_role_check
--   * add check workflows_status_check
--   * create index refresh_tokens_claims_idx
--   * create index users_email_key
--   * add FK workflows_owner_id_fkey

BEGIN;

CREATE TABLE refresh_tokens (
    token_hash TEXT NOT NULL,
    claims JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (token_hash)
);

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'member',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE workflows (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    owner_id BIGINT NOT NULL DEFAULT 0,
    title VARCHAR(255) NOT NULL,
    trigger_event VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

INSERT INTO users (id, email, password_hash, role)
OVERRIDING SYSTEM VALUE
VALUES (0, 'nobody@system', '', 'member')
ON CONFLICT DO NOTHING;

ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('admin', 'member'));

ALTER TABLE workflows ADD CONSTRAINT workflows_status_check CHECK (status IN ('draft', 'active', 'paused', 'archived'));

CREATE INDEX refresh_tokens_claims_idx ON refresh_tokens (claims);

CREATE UNIQUE INDEX users_email_key ON users (email);

ALTER TABLE workflows ADD CONSTRAINT workflows_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users (id);

COMMIT;
