-- Generated by yongol dev at 2026-04-24T02:26:11Z
-- Changes:
--   * create table actions
--   * create table execution_logs
--   * create table organizations
--   * create table users
--   * create table workflows
--   * create index idx_actions_workflow
--   * create index idx_execution_logs_workflow
--   * create index idx_execution_logs_org
--   * create index users_email_key
--   * create index idx_workflows_org_id
--   * create index idx_workflows_status
--   * add FK actions_workflow_id_fkey
--   * add FK execution_logs_workflow_id_fkey
--   * add FK execution_logs_org_id_fkey
--   * add FK users_org_id_fkey
--   * add FK workflows_org_id_fkey

BEGIN;

CREATE TABLE actions (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    workflow_id BIGINT NOT NULL,
    action_type VARCHAR(100) NOT NULL,
    payload_template TEXT NOT NULL DEFAULT '',
    sequence_order BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE execution_logs (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    workflow_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    credits_spent BIGINT NOT NULL DEFAULT 0,
    executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE organizations (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    plan_type VARCHAR(32) NOT NULL DEFAULT 'free',
    credits_balance BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL DEFAULT '',
    role VARCHAR(32) NOT NULL DEFAULT 'member',
    name VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE workflows (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    trigger_event VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_actions_workflow ON actions (workflow_id);

CREATE INDEX idx_execution_logs_workflow ON execution_logs (workflow_id);

CREATE INDEX idx_execution_logs_org ON execution_logs (org_id);

CREATE UNIQUE INDEX users_email_key ON users (email);

CREATE INDEX idx_workflows_org_id ON workflows (org_id);

CREATE INDEX idx_workflows_status ON workflows (status);

ALTER TABLE actions ADD CONSTRAINT actions_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows (id) ON DELETE CASCADE;

ALTER TABLE execution_logs ADD CONSTRAINT execution_logs_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows (id);

ALTER TABLE execution_logs ADD CONSTRAINT execution_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id);

ALTER TABLE users ADD CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id);

ALTER TABLE workflows ADD CONSTRAINT workflows_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id);

COMMIT;
