-- Generated by yongol v0.3.0 at 2026-05-11T00:26:39Z
-- Changes:
--   * create table actions
--   * create table execution_logs
--   * create table organizations
--   * create table refresh_tokens
--   * create table users
--   * create table workflows
--   * insert sentinel organizations
--   * insert sentinel workflows
--   * add check organizations_plan_type_check
--   * add check users_role_check
--   * add check workflows_status_check
--   * create index refresh_tokens_claims_idx
--   * create index users_email_key
--   * add FK actions_workflow_id_fkey
--   * add FK execution_logs_workflow_id_fkey
--   * add FK execution_logs_org_id_fkey
--   * add FK users_org_id_fkey
--   * add FK workflows_org_id_fkey

BEGIN;

CREATE TABLE actions (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    workflow_id BIGINT NOT NULL DEFAULT 0,
    action_type TEXT NOT NULL,
    config TEXT NOT NULL DEFAULT '',
    sequence_order BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE execution_logs (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    workflow_id BIGINT NOT NULL DEFAULT 0,
    org_id BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'success',
    credits_spent BIGINT NOT NULL DEFAULT 0,
    executed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE organizations (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name TEXT NOT NULL,
    plan_type TEXT NOT NULL DEFAULT 'free',
    credits_balance BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens (
    token_hash TEXT NOT NULL,
    claims JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (token_hash)
);

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE workflows (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    title TEXT NOT NULL,
    trigger_event TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

INSERT INTO organizations (id, name, plan_type, credits_balance)
OVERRIDING SYSTEM VALUE
VALUES (0, 'system', 'free', 0)
ON CONFLICT DO NOTHING;

INSERT INTO workflows (id, org_id, title, trigger_event, status)
OVERRIDING SYSTEM VALUE
VALUES (0, 0, 'system', 'none', 'draft')
ON CONFLICT DO NOTHING;

ALTER TABLE organizations ADD CONSTRAINT organizations_plan_type_check CHECK (plan_type IN ('free', 'pro', 'enterprise'));

ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('admin', 'member'));

ALTER TABLE workflows ADD CONSTRAINT workflows_status_check CHECK (status IN ('draft', 'active', 'paused', 'archived'));

CREATE INDEX refresh_tokens_claims_idx ON refresh_tokens USING gin (claims);

CREATE UNIQUE INDEX users_email_key ON users (email);

ALTER TABLE actions ADD CONSTRAINT actions_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows (id);

ALTER TABLE execution_logs ADD CONSTRAINT execution_logs_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows (id);

ALTER TABLE execution_logs ADD CONSTRAINT execution_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id);

ALTER TABLE users ADD CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id);

ALTER TABLE workflows ADD CONSTRAINT workflows_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id);

COMMIT;
