-- Generated by yongol v0.3.0 at 2026-05-11T00:36:08Z
-- Changes:
--   * add column workflows.root_workflow_id
--   * add column workflows.version

BEGIN;

ALTER TABLE workflows ADD COLUMN root_workflow_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE workflows ADD COLUMN version BIGINT NOT NULL DEFAULT 1;

COMMIT;
