-- Generated by yongol v0.3.0 at 2026-05-11T00:43:37Z
-- Changes:
--   * create table webhooks
--   * add FK webhooks_org_id_fkey

BEGIN;

CREATE TABLE webhooks (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    url TEXT NOT NULL,
    event_type TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE webhooks ADD CONSTRAINT webhooks_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id);

COMMIT;
