-- Generated by yongol v0.3.0 at 2026-05-11T00:47:18Z
-- Changes:
--   * create table templates
--   * create index idx_templates_source
--   * add FK templates_source_workflow_id_fkey
--   * add FK templates_org_id_fkey

BEGIN;

CREATE TABLE templates (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    source_workflow_id BIGINT NOT NULL DEFAULT 0,
    org_id BIGINT NOT NULL DEFAULT 0,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT '',
    clone_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_templates_source ON templates (source_workflow_id);

ALTER TABLE templates ADD CONSTRAINT templates_source_workflow_id_fkey FOREIGN KEY (source_workflow_id) REFERENCES workflows (id);

ALTER TABLE templates ADD CONSTRAINT templates_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id);

COMMIT;
