-- Generated by yongol v0.3.0 at 2026-05-11T00:50:10Z
-- Changes:
--   * create table audit_logs
--   * create index idx_audit_logs_org_id
--   * create index idx_audit_logs_created_at
--   * create index idx_audit_logs_action
--   * add FK audit_logs_org_id_fkey
--   * add FK audit_logs_actor_id_fkey

BEGIN;

CREATE TABLE audit_logs (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    actor_id BIGINT NOT NULL DEFAULT 0,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id BIGINT NOT NULL DEFAULT 0,
    detail TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_audit_logs_org_id ON audit_logs (org_id);

CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);

CREATE INDEX idx_audit_logs_action ON audit_logs (action);

ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id);

ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES users (id);

COMMIT;
