//ff:func feature=gen-fastapi type=test control=iteration dimension=1
//ff:what TestRenderPyproject — pyproject.toml / requirements.txt / 의존성 목록 생성 검증
package scaffold

import (
	"strings"
	"testing"
)

func TestRenderPyproject(t *testing.T) {
	out, err := RenderPyproject("myapp")
	if err != nil {
		t.Fatalf("RenderPyproject error: %v", err)
	}
	wants := []string{
		"[build-system]",
		`name = "myapp"`,
		`description = "myapp — generated by yongol"`,
		"dependencies = [",
		"[project.optional-dependencies]",
		"dev = [",
		"[tool.ruff]",
		"[tool.mypy]",
		`asyncio_mode = "auto"`,
	}
	for _, w := range wants {
		if !strings.Contains(out, w) {
			t.Errorf("pyproject missing %q\n%s", w, out)
		}
	}
	// runtime + dev deps embedded
	for _, d := range runtimeDependencies() {
		if !strings.Contains(out, d) {
			t.Errorf("runtime dep %q not embedded", d)
		}
	}
	for _, d := range devDependencies() {
		if !strings.Contains(out, d) {
			t.Errorf("dev dep %q not embedded", d)
		}
	}
}
