//ff:func feature=gen-fastapi type=generator control=iteration dimension=1
//ff:what RenderPyproject — FastAPI pyproject.toml 생성

package scaffold

import (
	"fmt"
	"strings"
)

// RenderPyproject produces the pyproject.toml content for a FastAPI project.
func RenderPyproject(projectID string) (string, error) {
	if projectID == "" {
		return "", fmt.Errorf("RenderPyproject: empty projectID")
	}

	var b strings.Builder

	b.WriteString("[build-system]\n")
	b.WriteString("requires = [\"setuptools>=68.0\", \"wheel\"]\n")
	b.WriteString("build-backend = \"setuptools.build_meta\"\n\n")

	b.WriteString("[project]\n")
	b.WriteString(fmt.Sprintf("name = \"%s\"\n", projectID))
	b.WriteString("version = \"0.1.0\"\n")
	b.WriteString(fmt.Sprintf("description = \"%s — generated by yongol\"\n", projectID))
	b.WriteString("requires-python = \">=3.11\"\n")
	b.WriteString("dependencies = [\n")
	for _, dep := range runtimeDependencies() {
		b.WriteString(fmt.Sprintf("    \"%s\",\n", dep))
	}
	b.WriteString("]\n\n")

	b.WriteString("[project.optional-dependencies]\n")
	b.WriteString("dev = [\n")
	for _, dep := range devDependencies() {
		b.WriteString(fmt.Sprintf("    \"%s\",\n", dep))
	}
	b.WriteString("]\n\n")

	b.WriteString("[tool.ruff]\n")
	b.WriteString("target-version = \"py311\"\n")
	b.WriteString("line-length = 88\n\n")

	b.WriteString("[tool.mypy]\n")
	b.WriteString("python_version = \"3.11\"\n")
	b.WriteString("strict = true\n\n")

	b.WriteString("[tool.pytest.ini_options]\n")
	b.WriteString("asyncio_mode = \"auto\"\n")

	return b.String(), nil
}
