//ff:func feature=gen-filefunc type=generator control=sequence
//ff:what writeCodebook — Codebook 구조체를 YAML 로 직렬화 후 파일로 기록
package filefunc

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// codebookHeader is prepended to every generated codebook.yaml so humans and
// AI tools see immediately that the file is machine-authored.
const codebookHeader = "# Auto-generated by yongol generate — do not edit manually.\n" +
	"# Regenerate with: yongol generate <specs> <arts>\n"

// writeCodebook serialises the given Codebook as YAML, prepends the header
// comment, and writes the result to path. Parent directories are created as
// needed.
func writeCodebook(path string, book Codebook) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir codebook dir: %w", err)
	}
	body, err := yaml.Marshal(book)
	if err != nil {
		return fmt.Errorf("marshal codebook: %w", err)
	}
	out := append([]byte(codebookHeader), body...)
	if err := os.WriteFile(path, out, 0o644); err != nil {
		return fmt.Errorf("write codebook: %w", err)
	}
	return nil
}
