// Code generated by yongol gen-model. DO NOT EDIT.
package geocoding

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

type GeocodingModel interface {
	Geocode(ctx context.Context, address string) (*GeocodingAPIResponse, error)
}

type GeocodingAPIResponse struct {
	FormattedAddress string  `json:"formatted_address"`
	Latitude         float32 `json:"latitude"`
	Longitude        float32 `json:"longitude"`
}

type geocodingClient struct {
	baseURL string
	client  *http.Client
}

func NewGeocodingModel(baseURL string) GeocodingModel {
	return &geocodingClient{baseURL: baseURL, client: &http.Client{}}
}

func (c *geocodingClient) Geocode(ctx context.Context, address string) (*GeocodingAPIResponse, error) {
	body := map[string]any{"address": address}
	var resp GeocodingAPIResponse
	if err := c.do(ctx, "POST", "/geocode", body, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *geocodingClient) do(ctx context.Context, method, path string, body any, result any) error {
	var buf bytes.Buffer
	if body != nil {
		if err := json.NewEncoder(&buf).Encode(body); err != nil {
			return fmt.Errorf("encode request: %w", err)
		}
	}
	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, &buf)
	if err != nil {
		return fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := c.client.Do(req)
	if err != nil {
		return fmt.Errorf("http %s %s: %w", method, path, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return fmt.Errorf("http %s %s: status %d", method, path, resp.StatusCode)
	}
	if result != nil {
		if err := json.NewDecoder(resp.Body).Decode(result); err != nil {
			return fmt.Errorf("decode response: %w", err)
		}
	}
	return nil
}
