//ff:func feature=validate type=rule control=sequence topic=ssac-structural
//ff:what Run — SSaC 검증 전체 실행 (S-*, XSS-*)
package ssac

import (
	"github.com/park-jun-woo/yongol/pkg/diagnostic"
	"github.com/park-jun-woo/yongol/pkg/yongol"
)

// Run executes all SSaC validation rules.
func Run(fs *yongol.Fullstack) []diagnostic.Diagnostic {
	var diags []diagnostic.Diagnostic
	diags = append(diags, s01GetModel(fs)...)
	diags = append(diags, s02GetResult(fs)...)
	diags = append(diags, s03PostModel(fs)...)
	diags = append(diags, s04PostResult(fs)...)
	diags = append(diags, s05PostInputs(fs)...)
	diags = append(diags, s06PutModel(fs)...)
	diags = append(diags, s07PutResult(fs)...)
	diags = append(diags, s08PutInputs(fs)...)
	diags = append(diags, s09DeleteModel(fs)...)
	diags = append(diags, s10DeleteResult(fs)...)
	diags = append(diags, s11DeleteNoInputs(fs)...)
	diags = append(diags, s12EmptyTarget(fs)...)
	diags = append(diags, s13EmptyMessage(fs)...)
	diags = append(diags, s14StateDiagramID(fs)...)
	diags = append(diags, s15StateInputs(fs)...)
	diags = append(diags, s16StateTransition(fs)...)
	diags = append(diags, s17StateMessage(fs)...)
	diags = append(diags, s18AuthAction(fs)...)
	diags = append(diags, s19AuthResource(fs)...)
	diags = append(diags, s20AuthMessage(fs)...)
	diags = append(diags, s21CallModel(fs)...)
	diags = append(diags, s23PublishTopic(fs)...)
	diags = append(diags, s24PublishPayload(fs)...)
	diags = append(diags, s25UnknownSeqType(fs)...)
	diags = append(diags, s26DotMethod(fs)...)
	diags = append(diags, s27VarDeclared(fs)...)
	diags = append(diags, s28TargetDeclared(fs)...)
	diags = append(diags, s29InputDeclared(fs)...)
	diags = append(diags, s30MessageDeclared(fs)...)
	diags = append(diags, s31ConfigPrefixForbidden(fs)...)
	diags = append(diags, s32PublishForbidden(fs)...)
	diags = append(diags, s33ReservedSource(fs)...)
	diags = append(diags, s34GoReservedWord(fs)...)
	diags = append(diags, s35GoReservedWordModel(fs)...)
	diags = append(diags, s36StaleResponse(fs)...)
	diags = append(diags, s37FKReferenceGuard(fs)...)
	diags = append(diags, s38SubscribeNoHTTPInputs(fs)...)
	diags = append(diags, s39SubscribeMessageRequired(fs)...)
	diags = append(diags, s40SubscribeSingleParam(fs)...)
	diags = append(diags, s41SubscribeNoCurrentUser(fs)...)
	diags = append(diags, s42SubscribeForbiddenRequest(fs)...)
	diags = append(diags, s43SubscribeForbiddenQuery(fs)...)
	diags = append(diags, s44HTTPForbiddenMessage(fs)...)
	diags = append(diags, s45SubscribeNoResponse(fs)...)
	diags = append(diags, s46UppercaseStart(fs)...)
	diags = append(diags, s47NoDotPrefix(fs)...)
	diags = append(diags, s48SymbolTableModel(fs)...)
	diags = append(diags, s49SymbolTableMethod(fs)...)
	diags = append(diags, s50OpenAPIRequest(fs)...)
	diags = append(diags, s51RequestUsage(fs)...)
	diags = append(diags, s57FuncRequestType(fs)...)
	diags = append(diags, s58InvalidErrStatus(fs)...)
	diags = append(diags, s59DottedField(fs)...)
	diags = append(diags, s60RequestFieldExact(fs)...)
	diags = append(diags, s61CodegenReservedVar(fs)...)
	diags = append(diags, s62UnusedResultVar(fs)...)
	diags = append(diags, s63ListNoPagination(fs)...)
	diags = append(diags, xss11PluralResultType(fs)...)
	diags = append(diags, xss38CallFuncLowercase(fs)...)
	diags = append(diags, xss47CallSourceVarUndefined(fs)...)
	diags = append(diags, xss57PublishToSubscribe(fs)...)
	diags = append(diags, xss58SubscribeToPublish(fs)...)
	diags = append(diags, xss59SubscribeFields(fs)...)
	return diags
}
