//ff:func feature=gen-gogin type=generator control=sequence
//ff:what renderLogValueFile — sqlc row 구조체용 LogValue() 메소드 파일 소스 생성

package sqlcpost

import (
	"fmt"
	"strings"

	"github.com/park-jun-woo/yongol/pkg/generate/gogin/ffannot"
	"github.com/park-jun-woo/yongol/pkg/parser/ddl"
)

// renderLogValueFile produces the full Go source for one <table>_log.go file.
// Uses Table.ColumnOrder for DDL-declared order; falls back to sorted
// Columns keys when ColumnOrder is empty (defensive).
//
// All non-sensitive fields are emitted as slog.Any (see slogAttrLine for
// rationale / BUG-024). The only typed constructor we keep is
// slog.String(name, "[REDACTED]") for sensitive columns, so the generated
// file only ever imports "log/slog".
func renderLogValueFile(t ddl.Table) (string, error) {
	structName := structNameFor(t.Name)
	cols := t.ColumnOrder
	if len(cols) == 0 {
		cols = sortedColumnKeys(t.Columns)
	}

	var b strings.Builder
	b.WriteString("// Code generated by yongol. DO NOT EDIT.\n")
	b.WriteString("// Sensitive-field log masking for sqlc row: ")
	b.WriteString(structName)
	b.WriteString("\n\n")
	b.WriteString(ffannot.EmitAnnotationBlock(ffannot.Block{
		Func: ffannot.FuncAnnot{
			Feature: "db",
			Type:    "util",
			Control: "sequence",
			Topic:   "observability",
		},
		What: structName + ".LogValue — sensitive 컬럼 [REDACTED] 마스킹 slog.Value 반환",
	}))
	b.WriteString("package db\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"log/slog\"\n")
	b.WriteString(")\n\n")

	// LogValue implementation.
	b.WriteString(fmt.Sprintf("// LogValue masks sensitive columns when this row is logged via slog.\n"))
	b.WriteString(fmt.Sprintf("// slog.LogValuer is invoked automatically by slog handlers, so ad-hoc calls\n"))
	b.WriteString(fmt.Sprintf("// like slog.Info(\"user\", \"u\", user) never emit the raw sensitive value.\n"))
	b.WriteString(fmt.Sprintf("func (r %s) LogValue() slog.Value {\n", structName))
	b.WriteString("\treturn slog.GroupValue(\n")
	writeLogValueFields(&b, t, cols)
	b.WriteString("\t)\n")
	b.WriteString("}\n")
	return b.String(), nil
}
