// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

//ff:func feature=db type=model control=sequence
//ff:what actionListByWorkflow
package db

const actionListByWorkflow = `-- name: ActionListByWorkflow :many
SELECT id, workflow_id, action_type, payload_template, sequence_order FROM actions WHERE workflow_id = $1 ORDER BY sequence_order ASC
`
