// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

//ff:func feature=db type=model control=sequence
//ff:what actionCreate
package db

const actionCreate = `-- name: ActionCreate :one
INSERT INTO actions (workflow_id, action_type, payload_template, sequence_order)
VALUES ($1, $2, $3, $4)
RETURNING id, workflow_id, action_type, payload_template, sequence_order
`
