// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

//ff:func feature=db type=model control=sequence
//ff:what executionLogFindByID
package db

const executionLogFindByID = `-- name: ExecutionLogFindByID :one
SELECT id, workflow_id, org_id, status, credits_spent, executed_at FROM execution_logs WHERE id = $1
`
