// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

//ff:func feature=db type=model control=sequence
//ff:what executionLogCreate
package db

const executionLogCreate = `-- name: ExecutionLogCreate :one
INSERT INTO execution_logs (workflow_id, org_id, status, credits_spent)
VALUES ($1, $2, $3, $4)
RETURNING id, workflow_id, org_id, status, credits_spent, executed_at
`
