// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what ExecutionLog
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExecutionLog struct {
	ID           int64
	WorkflowID   int64
	OrgID        int64
	Status       string
	CreditsSpent int64
	ExecutedAt   pgtype.Timestamp
}
