// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:type feature=db type=model
//ff:what OrganizationCreateParams
package db

type OrganizationCreateParams struct {
	Name           string
	PlanType       string
	CreditsBalance int64
}
