// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:func feature=db type=model control=sequence
//ff:what organizationUpdateCredits
package db

const organizationUpdateCredits = `-- name: OrganizationUpdateCredits :exec
UPDATE organizations SET credits_balance = $1 WHERE id = $2
`
