// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:type feature=db type=model
//ff:what OrganizationUpdateCreditsParams
package db

type OrganizationUpdateCreditsParams struct {
	CreditsBalance int64
	ID             int64
}
