// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:func feature=db type=model control=sequence
//ff:what organizationCreate
package db

const organizationCreate = `-- name: OrganizationCreate :one
INSERT INTO organizations (name, plan_type, credits_balance)
VALUES ($1, $2, $3)
RETURNING id, name, plan_type, credits_balance, created_at
`
