// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.WorkflowFindByID
//ff:checked llm=yongol-gen hash=3cf948fd
package db

import (
	"context"
)

func (q *Queries) WorkflowFindByID(ctx context.Context, id int64) (Workflow, error) {
	row := q.db.QueryRow(ctx, workflowFindByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.TriggerEvent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
