// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.RefreshTokenFindByHash
//ff:checked llm=yongol-gen hash=c1a30210
package db

import (
	"context"
)

func (q *Queries) RefreshTokenFindByHash(ctx context.Context, tokenHash string) (RefreshTokenFindByHashRow, error) {
	row := q.db.QueryRow(ctx, refreshTokenFindByHash, tokenHash)
	var i RefreshTokenFindByHashRow
	err := row.Scan(&i.Claims, &i.ExpiresAt, &i.RevokedAt)
	return i, err
}
