// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

//ff:func feature=db type=query control=sequence
//ff:what +allow-sensitive password_hash is required by auth login path
//ff:checked llm=yongol-gen hash=71bc04ee
package db

import (
	"context"
)

// +allow-sensitive password_hash is required by auth login path
func (q *Queries) UserFindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userFindByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
