// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.OrganizationFindByID
//ff:checked llm=yongol-gen hash=24e62c91
package db

import (
	"context"
)

func (q *Queries) OrganizationFindByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, organizationFindByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.CreditsBalance,
		&i.CreatedAt,
	)
	return i, err
}
