// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.OrganizationCreate
//ff:checked llm=yongol-gen hash=9c08b758
package db

import (
	"context"
)

func (q *Queries) OrganizationCreate(ctx context.Context, arg OrganizationCreateParams) (Organization, error) {
	row := q.db.QueryRow(ctx, organizationCreate, arg.Name, arg.PlanType, arg.CreditsBalance)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlanType,
		&i.CreditsBalance,
		&i.CreatedAt,
	)
	return i, err
}
