// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.WorkflowCreate
//ff:checked llm=yongol-gen hash=c9127534
package db

import (
	"context"
)

func (q *Queries) WorkflowCreate(ctx context.Context, arg WorkflowCreateParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, workflowCreate, arg.OwnerID, arg.Title, arg.TriggerEvent)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.TriggerEvent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
