// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=iteration dimension=1
//ff:what Queries.WorkflowListByOwnerID
//ff:checked llm=yongol-gen hash=a9de7c7a
package db

import (
	"context"
)

func (q *Queries) WorkflowListByOwnerID(ctx context.Context, arg WorkflowListByOwnerIDParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, workflowListByOwnerID, arg.OwnerID, arg.Page, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.TriggerEvent,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
