// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.WorkflowUpdateStatus
//ff:checked llm=yongol-gen hash=9ac3bf00
package db

import (
	"context"
)

func (q *Queries) WorkflowUpdateStatus(ctx context.Context, arg WorkflowUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, workflowUpdateStatus, arg.Status, arg.ID)
	return err
}
