// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.RefreshTokenRevoke
//ff:checked llm=yongol-gen hash=33485e93
package db

import (
	"context"
)

func (q *Queries) RefreshTokenRevoke(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, refreshTokenRevoke, tokenHash)
	return err
}
