// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

//ff:func feature=db type=query control=sequence
//ff:what +allow-sensitive password_hash is required by auth middleware
//ff:checked llm=yongol-gen hash=d63e11a6
package db

import (
	"context"
)

// +allow-sensitive password_hash is required by auth middleware
func (q *Queries) UserFindByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, userFindByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
