// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.WorkflowCountByOwnerID
//ff:checked llm=yongol-gen hash=6f34a27e
package db

import (
	"context"
)

func (q *Queries) WorkflowCountByOwnerID(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, workflowCountByOwnerID, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
