// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.ExecutionLogFindByID
//ff:checked llm=yongol-gen hash=c4e17bda
package db

import (
	"context"
)

func (q *Queries) ExecutionLogFindByID(ctx context.Context, id int64) (ExecutionLog, error) {
	row := q.db.QueryRow(ctx, executionLogFindByID, id)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.CreditsSpent,
		&i.ExecutedAt,
	)
	return i, err
}
