// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.WorkflowCreate
//ff:checked llm=yongol-gen hash=6e5f559c
package db

import (
	"context"
)

func (q *Queries) WorkflowCreate(ctx context.Context, arg WorkflowCreateParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, workflowCreate,
		arg.OrgID,
		arg.Title,
		arg.TriggerEvent,
		arg.Status,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.TriggerEvent,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
