// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.RefreshTokenInsert
//ff:checked llm=yongol-gen hash=afbda210
package db

import (
	"context"
)

func (q *Queries) RefreshTokenInsert(ctx context.Context, arg RefreshTokenInsertParams) error {
	_, err := q.db.Exec(ctx, refreshTokenInsert, arg.TokenHash, arg.Claims, arg.ExpiresAt)
	return err
}
