// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.ActionCreate
//ff:checked llm=yongol-gen hash=5468c84e
package db

import (
	"context"
)

func (q *Queries) ActionCreate(ctx context.Context, arg ActionCreateParams) (Action, error) {
	row := q.db.QueryRow(ctx, actionCreate,
		arg.WorkflowID,
		arg.ActionType,
		arg.PayloadTemplate,
		arg.SequenceOrder,
	)
	var i Action
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.ActionType,
		&i.PayloadTemplate,
		&i.SequenceOrder,
	)
	return i, err
}
