// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.RefreshTokenRevokeAll
//ff:checked llm=yongol-gen hash=4927e3d4
package db

import (
	"context"
)

func (q *Queries) RefreshTokenRevokeAll(ctx context.Context, matcher []byte) error {
	_, err := q.db.Exec(ctx, refreshTokenRevokeAll, matcher)
	return err
}
