// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.OrganizationUpdateCredits
//ff:checked llm=yongol-gen hash=9555402f
package db

import (
	"context"
)

func (q *Queries) OrganizationUpdateCredits(ctx context.Context, arg OrganizationUpdateCreditsParams) error {
	_, err := q.db.ExecContext(ctx, organizationUpdateCredits, arg.CreditsBalance, arg.ID)
	return err
}
