// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.UserFindByID
//ff:checked llm=yongol-gen hash=0aaa8077
package db

import (
	"context"
)

func (q *Queries) UserFindByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, userFindByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
