// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.UserCreate
//ff:checked llm=yongol-gen hash=d8d09311
package db

import (
	"context"
)

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRow(ctx, userCreate,
		arg.OrgID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
