// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	LoginLookup(ctx context.Context, email string) (LoginLookupRow, error)
	RefreshTokenFindByHash(ctx context.Context, tokenHash string) (RefreshTokenFindByHashRow, error)
	RefreshTokenInsert(ctx context.Context, arg RefreshTokenInsertParams) error
	RefreshTokenRevoke(ctx context.Context, tokenHash string) error
	RefreshTokenRevokeAll(ctx context.Context, matcher []byte) error
	UserCreate(ctx context.Context, arg UserCreateParams) (User, error)
	UserFindByEmail(ctx context.Context, email string) (User, error)
	UserFindByID(ctx context.Context, id int64) (User, error)
	WorkflowCountByOwnerID(ctx context.Context, ownerID int64) (int64, error)
	WorkflowCreate(ctx context.Context, arg WorkflowCreateParams) (Workflow, error)
	WorkflowFindByID(ctx context.Context, id int64) (Workflow, error)
	WorkflowListByOwnerID(ctx context.Context, arg WorkflowListByOwnerIDParams) ([]Workflow, error)
	WorkflowUpdateStatus(ctx context.Context, arg WorkflowUpdateStatusParams) error
}

var _ Querier = (*Queries)(nil)
