// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

//ff:type feature=db type=model
//ff:what RefreshTokenInsertParams
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshTokenInsertParams struct {
	TokenHash string             `json:"token_hash"`
	Claims    []byte             `json:"claims"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}
