// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

//ff:type feature=db type=model
//ff:what RefreshTokenFindByHashRow
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshTokenFindByHashRow struct {
	Claims    []byte             `json:"claims"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}
