// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what RefreshToken
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	TokenHash string             `json:"token_hash"`
	Claims    []byte             `json:"claims"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
