// Code generated by yongol. DO NOT EDIT.
// Sensitive-field log masking for sqlc row: RefreshToken

//ff:func feature=db type=util control=sequence topic=observability
//ff:what RefreshToken.LogValue — sensitive 컬럼 [REDACTED] 마스킹 slog.Value 반환
//ff:checked llm=yongol-gen hash=9797c2f0
package db

import (
	"log/slog"
)

// LogValue masks sensitive columns when this row is logged via slog.
// slog.LogValuer is invoked automatically by slog handlers, so ad-hoc calls
// like slog.Info("user", "u", user) never emit the raw sensitive value.
func (r RefreshToken) LogValue() slog.Value {
	return slog.GroupValue(
		slog.String("token_hash", "[REDACTED]"),
		slog.Any("claims", r.Claims),
		slog.Any("expires_at", r.ExpiresAt),
		slog.Any("revoked_at", r.RevokedAt),
		slog.Any("created_at", r.CreatedAt),
	)
}
