// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

//ff:func feature=db type=model control=sequence
//ff:what refreshTokenInsert
package db

const refreshTokenInsert = `-- name: RefreshTokenInsert :exec
INSERT INTO refresh_tokens (token_hash, claims, expires_at)
VALUES ($1, $2, $3)
`
