// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what User
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
