// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

//ff:func feature=db type=model control=sequence
//ff:what userFindByID
package db

const userFindByID = `-- name: UserFindByID :one
SELECT id, org_id, email, password_hash, role, name, created_at FROM users WHERE id = $1
`
