// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what User
package db

import (
	"time"
)

type User struct {
	ID           int64
	OrgID        int64
	Email        string
	PasswordHash string
	Role         string
	Name         string
	CreatedAt    time.Time
}
