// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

//ff:type feature=db type=model
//ff:what UserCreateParams
package db

type UserCreateParams struct {
	OrgID        int64
	Email        string
	PasswordHash string
	Role         string
	Name         string
}
