// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

//ff:func feature=db type=model control=sequence
//ff:what userFindByEmail
package db

const userFindByEmail = `-- name: UserFindByEmail :one
SELECT id, org_id, email, password_hash, role, name, created_at FROM users WHERE email = $1
`
