// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:type feature=db type=model
//ff:what WorkflowUpdateStatusParams
package db

type WorkflowUpdateStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}
