// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what workflowListByOwnerID
package db

const workflowListByOwnerID = `-- name: WorkflowListByOwnerID :many
SELECT id, owner_id, title, trigger_event, status, created_at
FROM workflows
WHERE owner_id = $1
ORDER BY id DESC
LIMIT $3 OFFSET ($2::int - 1) * $3
`
