// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what Workflow
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Workflow struct {
	ID           int64              `json:"id"`
	OwnerID      int64              `json:"owner_id"`
	Title        string             `json:"title"`
	TriggerEvent string             `json:"trigger_event"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
