// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what workflowCreate
package db

const workflowCreate = `-- name: WorkflowCreate :one
INSERT INTO workflows (owner_id, title, trigger_event, status)
VALUES ($1, $2, $3, 'draft')
RETURNING id, owner_id, title, trigger_event, status, created_at
`
