// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:type feature=db type=model
//ff:what WorkflowListByOwnerIDParams
package db

type WorkflowListByOwnerIDParams struct {
	OwnerID int64 `json:"owner_id"`
	Page    int32 `json:"page"`
	PerPage int32 `json:"per_page"`
}
