// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:type feature=db type=model
//ff:what WorkflowCreateParams
package db

type WorkflowCreateParams struct {
	OwnerID      int64  `json:"owner_id"`
	Title        string `json:"title"`
	TriggerEvent string `json:"trigger_event"`
}
