// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what workflowUpdateStatus
package db

const workflowUpdateStatus = `-- name: WorkflowUpdateStatus :exec
UPDATE workflows SET status = $1 WHERE id = $2
`
