// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what workflowCountByOwnerID
package db

const workflowCountByOwnerID = `-- name: WorkflowCountByOwnerID :one
SELECT COUNT(*) FROM workflows WHERE owner_id = $1
`
