-- YONGOL_SCHEMA_HASH: 6db03eefc5403f2f67bcc297b49903f2a66a8accafb02727765597ae2c662ff1
-- Generated by yongol v0.3.0 at 2026-05-11T00:50:10Z

CREATE TABLE actions (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    workflow_id BIGINT NOT NULL DEFAULT 0,
    action_type TEXT NOT NULL,
    config TEXT NOT NULL DEFAULT '',
    sequence_order BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT actions_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows (id)
);


CREATE TABLE audit_logs (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    actor_id BIGINT NOT NULL DEFAULT 0,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id BIGINT NOT NULL DEFAULT 0,
    detail TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT audit_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id),
    CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES users (id)
);
CREATE INDEX idx_audit_logs_action ON audit_logs (action);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX idx_audit_logs_org_id ON audit_logs (org_id);


CREATE TABLE execution_logs (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    workflow_id BIGINT NOT NULL DEFAULT 0,
    org_id BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'success',
    credits_spent BIGINT NOT NULL DEFAULT 0,
    executed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT execution_logs_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows (id),
    CONSTRAINT execution_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id)
);


CREATE TABLE organizations (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name TEXT NOT NULL,
    plan_type TEXT NOT NULL DEFAULT 'free',
    credits_balance BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT organizations_plan_type_check CHECK (plan_type IN ('free', 'pro', 'enterprise'))
);

INSERT INTO organizations (id, name, plan_type, credits_balance)
OVERRIDING SYSTEM VALUE
VALUES (0, 'system', 'free', 0)
ON CONFLICT DO NOTHING;


CREATE TABLE refresh_tokens (
    token_hash TEXT NOT NULL,
    claims JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (token_hash)
);
CREATE INDEX refresh_tokens_claims_idx ON refresh_tokens USING gin (claims);


CREATE TABLE templates (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    source_workflow_id BIGINT NOT NULL DEFAULT 0,
    org_id BIGINT NOT NULL DEFAULT 0,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT '',
    clone_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT templates_source_workflow_id_fkey FOREIGN KEY (source_workflow_id) REFERENCES workflows (id),
    CONSTRAINT templates_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id)
);
CREATE UNIQUE INDEX idx_templates_source ON templates (source_workflow_id);


CREATE TABLE users (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id),
    CONSTRAINT users_role_check CHECK (role IN ('admin', 'member'))
);

INSERT INTO users (id, org_id, email, password_hash, role)
OVERRIDING SYSTEM VALUE
VALUES (0, 0, 'nobody@system', '', 'member')
ON CONFLICT DO NOTHING;
CREATE UNIQUE INDEX users_email_key ON users (email);


CREATE TABLE webhooks (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    url TEXT NOT NULL,
    event_type TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT webhooks_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id)
);


CREATE TABLE workflows (
    id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    org_id BIGINT NOT NULL DEFAULT 0,
    title TEXT NOT NULL,
    trigger_event TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    version BIGINT NOT NULL DEFAULT 1,
    root_workflow_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT workflows_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id),
    CONSTRAINT workflows_status_check CHECK (status IN ('draft', 'active', 'paused', 'archived'))
);

INSERT INTO workflows (id, org_id, title, trigger_event, status, version, root_workflow_id)
OVERRIDING SYSTEM VALUE
VALUES (0, 0, 'system', 'none', 'draft', 1, 0)
ON CONFLICT DO NOTHING;

