// Generated by yongol. Do not edit.
// Source of truth: specs/api/openapi.yaml (operationId-keyed).
import createClient from 'openapi-fetch'
import type { paths } from './types/api'

const client = createClient<paths>({ baseUrl: '/api' })

export const apiClient = {
  ActivateWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/workflows/{id}/activate' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  AddAction: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/workflows/{id}/actions' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  CreateWorkflow: (args?: Record<string, any>) => {
    return client.POST('/workflows' as any, { body: args ?? {} } as any).then(r => (r as any).data)
  },
  ExecuteWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/workflows/{id}/execute' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  GetCurrentUser: (args?: Record<string, any>) => {
    return client.GET('/users/me' as any, { params: { query: args ?? {} } } as any).then(r => (r as any).data)
  },
  ListWorkflows: (args?: Record<string, any>) => {
    return client.GET('/workflows' as any, { params: { query: args ?? {} } } as any).then(r => (r as any).data)
  },
  Login: (args?: Record<string, any>) => {
    return client.POST('/auth/login' as any, { body: args ?? {} } as any).then(r => (r as any).data)
  },
  Signup: (args?: Record<string, any>) => {
    return client.POST('/auth/signup' as any, { body: args ?? {} } as any).then(r => (r as any).data)
  },
}
