// Generated by yongol. Do not edit.
// Source of truth: specs/api/openapi.yaml (operationId-keyed).
import createClient from 'openapi-fetch'
import type { paths } from '../types/api'

const client = createClient<paths>({ baseUrl: '/api' })

export const api = {
  ActivateWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/activate', { params: { path }, body }).then(r => r.data)
  },
  ArchiveWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/archive', { params: { path }, body }).then(r => r.data)
  },
  CloneTemplate: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/templates/{id}/clone', { params: { path }, body }).then(r => r.data)
  },
  CreateAction: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/actions', { params: { path }, body }).then(r => r.data)
  },
  CreateWebhook: (args?: Record<string, any>) => {
    return client.POST('/api/webhooks', { body: args ?? {} }).then(r => r.data)
  },
  CreateWorkflow: (args?: Record<string, any>) => {
    return client.POST('/api/workflows', { body: args ?? {} }).then(r => r.data)
  },
  CreateWorkflowVersion: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/new-version', { params: { path }, body }).then(r => r.data)
  },
  DeleteWebhook: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.DELETE('/api/webhooks/{id}', { params: { path }, body }).then(r => r.data)
  },
  ExecuteWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/execute', { params: { path }, body }).then(r => r.data)
  },
  GetDashboard: (args?: Record<string, any>) => {
    return client.GET('/api/dashboard', { params: { query: args ?? {} } }).then(r => r.data)
  },
  GetTemplate: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/templates/{id}', { params: { path, query } }).then(r => r.data)
  },
  GetWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/workflows/{id}', { params: { path, query } }).then(r => r.data)
  },
  ListActions: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/workflows/{id}/actions', { params: { path, query } }).then(r => r.data)
  },
  ListAuditLogs: (args?: Record<string, any>) => {
    return client.GET('/api/audit-logs', { params: { query: args ?? {} } }).then(r => r.data)
  },
  ListExecutionLogs: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/workflows/{id}/logs', { params: { path, query } }).then(r => r.data)
  },
  ListTemplates: (args?: Record<string, any>) => {
    return client.GET('/api/templates', { params: { query: args ?? {} } }).then(r => r.data)
  },
  ListWebhooks: (args?: Record<string, any>) => {
    return client.GET('/api/webhooks', { params: { query: args ?? {} } }).then(r => r.data)
  },
  ListWorkflowVersions: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/workflows/{id}/versions', { params: { path, query } }).then(r => r.data)
  },
  ListWorkflows: (args?: Record<string, any>) => {
    return client.GET('/api/workflows', { params: { query: args ?? {} } }).then(r => r.data)
  },
  Login: (args?: Record<string, any>) => {
    return client.POST('/auth/login', { body: args ?? {} }).then(r => r.data)
  },
  PauseWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/pause', { params: { path }, body }).then(r => r.data)
  },
  PublishTemplate: (args?: Record<string, any>) => {
    return client.POST('/api/templates', { body: args ?? {} }).then(r => r.data)
  },
  Register: (args?: Record<string, any>) => {
    return client.POST('/auth/register', { body: args ?? {} }).then(r => r.data)
  },
}
