// Generated by yongol. Do not edit.
// Source of truth: specs/api/openapi.yaml (operationId-keyed).
import createClient from 'openapi-fetch'
import type { paths } from '../types/api'

const client = createClient<paths>({ baseUrl: '/api' })

export const api = {
  ActivateWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/activate' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  ArchiveWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/archive' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  CloneTemplate: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/templates/{id}/clone' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  CreateAction: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/actions' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  CreateWebhook: (args?: Record<string, any>) => {
    return client.POST('/api/webhooks' as any, { body: args ?? {} } as any).then(r => (r as any).data)
  },
  CreateWorkflow: (args?: Record<string, any>) => {
    return client.POST('/api/workflows' as any, { body: args ?? {} } as any).then(r => (r as any).data)
  },
  CreateWorkflowVersion: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/new-version' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  DeleteWebhook: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.DELETE('/api/webhooks/{id}' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  ExecuteWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/execute' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  GetDashboard: (args?: Record<string, any>) => {
    return client.GET('/api/dashboard' as any, { params: { query: args ?? {} } } as any).then(r => (r as any).data)
  },
  GetTemplate: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/templates/{id}' as any, { params: { path, query } } as any).then(r => (r as any).data)
  },
  GetWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/workflows/{id}' as any, { params: { path, query } } as any).then(r => (r as any).data)
  },
  ListActions: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/workflows/{id}/actions' as any, { params: { path, query } } as any).then(r => (r as any).data)
  },
  ListAuditLogs: (args?: Record<string, any>) => {
    return client.GET('/api/audit-logs' as any, { params: { query: args ?? {} } } as any).then(r => (r as any).data)
  },
  ListExecutionLogs: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/workflows/{id}/logs' as any, { params: { path, query } } as any).then(r => (r as any).data)
  },
  ListTemplates: (args?: Record<string, any>) => {
    return client.GET('/api/templates' as any, { params: { query: args ?? {} } } as any).then(r => (r as any).data)
  },
  ListWebhooks: (args?: Record<string, any>) => {
    return client.GET('/api/webhooks' as any, { params: { query: args ?? {} } } as any).then(r => (r as any).data)
  },
  ListWorkflowVersions: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const query: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (v == null) continue
        if (!(k in path)) query[k] = v
      }
    }
    return client.GET('/api/workflows/{id}/versions' as any, { params: { path, query } } as any).then(r => (r as any).data)
  },
  ListWorkflows: (args?: Record<string, any>) => {
    return client.GET('/api/workflows' as any, { params: { query: args ?? {} } } as any).then(r => (r as any).data)
  },
  Login: (args?: Record<string, any>) => {
    return client.POST('/auth/login' as any, { body: args ?? {} } as any).then(r => (r as any).data)
  },
  PauseWorkflow: (args?: Record<string, any>) => {
    const path: Record<string, any> = {}
    if (args && args['id'] !== undefined) path['id'] = args['id']
    const body: Record<string, any> = {}
    if (args) {
      for (const [k, v] of Object.entries(args)) {
        if (!(k in path)) body[k] = v
      }
    }
    return client.POST('/api/workflows/{id}/pause' as any, { params: { path }, body } as any).then(r => (r as any).data)
  },
  PublishTemplate: (args?: Record<string, any>) => {
    return client.POST('/api/templates' as any, { body: args ?? {} } as any).then(r => (r as any).data)
  },
  Register: (args?: Record<string, any>) => {
    return client.POST('/auth/register' as any, { body: args ?? {} } as any).then(r => (r as any).data)
  },
}
