//ff:func feature=gen-gogin type=util control=sequence
//ff:what buildAuth — @auth 시퀀스 빌더 (authz.Check 에 currentUser 를 Claim 으로 전달)

package ssac

import (
	"fmt"
	ssacparser "github.com/park-jun-woo/yongol/pkg/parser/ssac"
)

// buildAuth emits an authz.Check call that passes the entire *model.UserClaim
// struct as the `Claim` field. ssac/pkg/authz forwards it to OPA unchanged;
// rego.Input json-marshals the struct using its JSON tags (generated by
// generate_user_claim.go) into the `input.claims` object expected by rego.
//
// Phase002 (ssac/purify) — authz.CheckRequest.Tx has been removed from
// ssac because the package is now DB-free. Ownership lookups are performed
// by the handler before Check (Phase003) and populate CheckRequest.Owners.
// This emitter therefore:
//
//   - Drops the Tx field entirely from the literal.
//   - Leaves the Owners field unset for now. Phase003 will replace this
//     emitter with one that runs the per-ownership OwnerLookup<Resource>
//     sqlc queries and builds the owners map before Check.
func (g *methodGen) buildAuth(seq ssacparser.Sequence) ([]string, []string) {
	status := resolveErrStatus("auth", seq.ErrStatus)
	msg := seq.Message
	if msg == "" {
		msg = neutralMessage(status)
	}
	fields := g.mapFields(seq.Inputs)
	assign := g.assignOp(false)
	lines := []string{
		fmt.Sprintf("_, err %s authz.Check(authz.CheckRequest{Ctx: ctx, Action: %q, Resource: %q, Claim: currentUser, %s})", assign, seq.Action, seq.Resource, fields),
		"if err != nil {",
		fmt.Sprintf("\t%s(\"handler: %s\", \"op\", %q, \"status\", %d, \"err\", err)", logLevelFuncForStatus(status), logTagForStatus(status), g.FuncName, status),
		fmt.Sprintf("\treturn api.%s%dJSONResponse{Error: %q, Code: strPtr(%q)}, nil", g.FuncName, status, msg, neutralCode(status)),
		"}",
	}
	return lines, []string{`"github.com/park-jun-woo/ssac/pkg/authz"`, `"log/slog"`}
}
