//ff:func feature=gen-gogin type=test control=sequence topic=response
//ff:what TestBuildResponse_Empty204 — 204 빈 응답은 Response suffix 사용 (BUG-053)

package ssac

import (
	"strings"
	"testing"

	ssacparser "github.com/park-jun-woo/yongol/pkg/parser/ssac"
)

// TestBuildResponse_Empty204 verifies that buildResponse for an empty 204
// response uses api.<Op>204Response{} (not JSONResponse), matching the
// type generated by oapi-codegen for body-less responses.
func TestBuildResponse_Empty204(t *testing.T) {
	g := &methodGen{
		FuncName:      "DeleteWebhook",
		SuccessStatus: 204,
		RespFields:    make(map[string]responseField),
		VarTypes:      map[string]string{},
	}
	seq := ssacparser.Sequence{
		Type:         "response",
		SuppressWarn: true,
	}
	lines, _ := g.buildResponse(seq)
	body := strings.Join(lines, "\n")

	want := "return api.DeleteWebhook204Response{}, nil"
	if !strings.Contains(body, want) {
		t.Fatalf("expected %q, got:\n%s", want, body)
	}
	// Must NOT contain JSONResponse for 204.
	if strings.Contains(body, "JSONResponse") {
		t.Fatalf("204 must not use JSONResponse suffix, got:\n%s", body)
	}
}
