//ff:func feature=gen-gogin type=util control=sequence
//ff:what buildAuth — @auth 시퀀스 빌더 (authz.Check 에 currentUser 를 Claim 으로 전달)

package ssac

import (
	"fmt"
	ssacparser "github.com/park-jun-woo/yongol/pkg/parser/ssac"
)

// buildAuth emits an authz.Check call that passes the entire *model.UserClaim
// struct as the `Claim` field. ssac/pkg/authz forwards it to OPA unchanged;
// rego.Input json-marshals the struct using its JSON tags (generated by
// generate_user_claim.go) into the `input.claims` object expected by rego.
//
// Phase005 pgx/v5 refit — handlers now open pgx.Tx but authz.CheckRequest.Tx
// is typed *sql.Tx in ssac/pkg/authz. Until that package is ported to pgx
// (separate follow-up), the Tx field is left nil so loadOwners falls back
// to globalDB. MVCC-snapshot alignment with in-tx writes is temporarily
// lost; the authz check sees committed rows only. This is acceptable for
// @auth on read-only resources and the ownership lookups that zenflow
// exercises (@auth precedes mutation sequences). Switching authz to pgx is
// tracked alongside auth/queue migration.
func (g *methodGen) buildAuth(seq ssacparser.Sequence) ([]string, []string) {
	status := resolveErrStatus("auth", seq.ErrStatus)
	msg := seq.Message
	if msg == "" {
		msg = neutralMessage(status)
	}
	fields := g.mapFields(seq.Inputs)
	assign := g.assignOp(false)
	txArg := "nil"
	lines := []string{
		fmt.Sprintf("_, err %s authz.Check(authz.CheckRequest{Ctx: ctx, Tx: %s, Action: %q, Resource: %q, Claim: currentUser, %s})", assign, txArg, seq.Action, seq.Resource, fields),
		"if err != nil {",
		fmt.Sprintf("\t%s(\"handler: %s\", \"op\", %q, \"status\", %d, \"err\", err)", logLevelFuncForStatus(status), logTagForStatus(status), g.FuncName, status),
		fmt.Sprintf("\treturn api.%s%dJSONResponse{Error: %q, Code: strPtr(%q)}, nil", g.FuncName, status, msg, neutralCode(status)),
		"}",
	}
	return lines, []string{`"github.com/park-jun-woo/ssac/pkg/authz"`, `"log/slog"`}
}
