//ff:func feature=gen-hurl type=util control=iteration dimension=1
//ff:what writeSmokeHurl — step 목록을 arts/tests/smoke.hurl 파일로 출력
package hurl

import (
	"os"
	"path/filepath"
	"strings"
)

// writeSmokeHurl writes all steps to artifactsDir/tests/smoke.hurl.
func writeSmokeHurl(steps []step, artifactsDir string) error {
	dir := filepath.Join(artifactsDir, "tests")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# Auto-generated by yongol generate — do not edit.\n")
	b.WriteString("# Run: hurl --test --variable host=http://localhost:8080 smoke.hurl\n")
	for _, s := range steps {
		b.WriteString("\n")
		b.WriteString(writeStep(s))
	}
	return os.WriteFile(filepath.Join(dir, "smoke.hurl"), []byte(b.String()), 0o644)
}
