//ff:func feature=gen-react type=generator control=sequence
//ff:what src/lib/utils.ts 방출 — cn() 헬퍼 (clsx + tailwind-merge)

package react

import (
	"os"
	"path/filepath"
)

// writeLibUtils emits the canonical shadcn/ui `cn()` helper used by every
// components/ui/* primitive. Keeping a single source prevents drift when
// primitives are regenerated.
func writeLibUtils(srcDir string) error {
	const src = `// Generated by yongol. Canonical shadcn/ui cn() helper.
// Combines clsx (conditional classes) with tailwind-merge (conflict resolution).
import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`
	dir := filepath.Join(srcDir, "lib")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "utils.ts"), []byte(src), 0o644)
}
