//ff:func feature=gen-react type=generator control=iteration dimension=2
//ff:what renderBreadcrumbsTS — src/lib/breadcrumbs.ts 소스 생성 (Crumb 타입 + BREADCRUMBS trail 테이블 + 라우트 매칭 테이블, dynamic 슬롯 조건부)

package react

import (
	"fmt"
	"strings"
)

// renderBreadcrumbsTS renders the src/lib/breadcrumbs.ts source
// (plans/stml/sitemap Phase004): the Crumb shape, the page-name-keyed
// BREADCRUMBS trail table (the plan's TS form — generate-time constants,
// no runtime tree walk) and the BREADCRUMB_ROUTES pattern → page matching
// table the <Breadcrumb> component scans (specificity-sorted via
// sortBreadcrumbRoutes). Pages absent from the table — unlisted in the
// sitemap or depth 1 — simply never match, so no breadcrumb renders for
// them. dynamic (Phase006 — the sitemap declares some data-crumb-field)
// extends the Crumb shape with the optional dynamic flag and marks each
// trail's Dynamic self crumb; false keeps the Phase004 bytes identical.
func renderBreadcrumbsTS(trails []breadcrumbTrail, dynamic bool) string {
	var sb strings.Builder
	sb.WriteString("// Generated by yongol. Do not edit.\n")
	sb.WriteString("// Static breadcrumb trails derived from frontend/sitemap.html (root → self labels).\n\n")
	if dynamic {
		sb.WriteString("export interface Crumb {\n  label: string\n  href?: string\n  dynamic?: boolean\n}\n\n")
	} else {
		sb.WriteString("export interface Crumb {\n  label: string\n  href?: string\n}\n\n")
	}
	if len(trails) == 0 {
		sb.WriteString("export const BREADCRUMBS: Record<string, Crumb[]> = {}\n\n")
		sb.WriteString("export const BREADCRUMB_ROUTES: { pattern: string; page: string }[] = []\n")
		return sb.String()
	}
	sb.WriteString("export const BREADCRUMBS: Record<string, Crumb[]> = {\n")
	for _, t := range trails {
		fmt.Fprintf(&sb, "  %s: [\n", tsSingleQuote(t.Page))
		for _, c := range t.Crumbs {
			parts := []string{fmt.Sprintf("label: %s", tsSingleQuote(c.Label))}
			if c.Href != "" {
				parts = append(parts, fmt.Sprintf("href: %s", tsSingleQuote(c.Href)))
			}
			if c.Dynamic {
				parts = append(parts, "dynamic: true")
			}
			fmt.Fprintf(&sb, "    { %s },\n", strings.Join(parts, ", "))
		}
		sb.WriteString("  ],\n")
	}
	sb.WriteString("}\n\n")
	sb.WriteString("export const BREADCRUMB_ROUTES: { pattern: string; page: string }[] = [\n")
	for _, t := range sortBreadcrumbRoutes(trails) {
		fmt.Fprintf(&sb, "  { pattern: %s, page: %s },\n", tsSingleQuote(t.Pattern), tsSingleQuote(t.Page))
	}
	sb.WriteString("]\n")
	return sb.String()
}
