//ff:func feature=gen-react type=test control=sequence
//ff:what renderBreadcrumbsTS — trail 테이블 + 정렬된 라우트 매칭 테이블 전체 스냅샷 / 빈 trail 출력 검증

package react

import "testing"

func TestRenderBreadcrumbsTS(t *testing.T) {
	trails := []breadcrumbTrail{
		{Page: "building-detail", Pattern: "/buildings/:BuildingID", Crumbs: []breadcrumbCrumb{
			{Label: "건물 관리"},
			{Label: "건물 목록", Href: "/buildings"},
			{Label: "건물 상세"},
		}},
		{Page: "building-new", Pattern: "/buildings/new", Crumbs: []breadcrumbCrumb{
			{Label: "건물 목록", Href: "/buildings"},
			{Label: "건물 등록"},
		}},
	}

	t.Run("full snapshot", func(t *testing.T) {
		want := "// Generated by yongol. Do not edit.\n" +
			"// Static breadcrumb trails derived from frontend/sitemap.html (root → self labels).\n" +
			"\n" +
			"export interface Crumb {\n" +
			"  label: string\n" +
			"  href?: string\n" +
			"}\n" +
			"\n" +
			"export const BREADCRUMBS: Record<string, Crumb[]> = {\n" +
			"  'building-detail': [\n" +
			"    { label: '건물 관리' },\n" +
			"    { label: '건물 목록', href: '/buildings' },\n" +
			"    { label: '건물 상세' },\n" +
			"  ],\n" +
			"  'building-new': [\n" +
			"    { label: '건물 목록', href: '/buildings' },\n" +
			"    { label: '건물 등록' },\n" +
			"  ],\n" +
			"}\n" +
			"\n" +
			"export const BREADCRUMB_ROUTES: { pattern: string; page: string }[] = [\n" +
			"  { pattern: '/buildings/new', page: 'building-new' },\n" + // static pattern first
			"  { pattern: '/buildings/:BuildingID', page: 'building-detail' },\n" +
			"]\n"
		if got := renderBreadcrumbsTS(trails, false); got != want {
			t.Errorf("got:\n%s\nwant:\n%s", got, want)
		}
	})

	t.Run("no trails emits empty tables", func(t *testing.T) {
		got := renderBreadcrumbsTS(nil, false)
		assertContains(t, got, "export const BREADCRUMBS: Record<string, Crumb[]> = {}")
		assertContains(t, got, "export const BREADCRUMB_ROUTES: { pattern: string; page: string }[] = []")
	})

	t.Run("dynamic extends the Crumb shape and marks the self crumb", func(t *testing.T) {
		dyn := []breadcrumbTrail{
			{Page: "building-detail", Pattern: "/buildings/:BuildingID", Crumbs: []breadcrumbCrumb{
				{Label: "건물 목록", Href: "/buildings"},
				{Label: "건물 상세", Dynamic: true},
			}},
		}
		got := renderBreadcrumbsTS(dyn, true)
		assertContains(t, got, "export interface Crumb {\n  label: string\n  href?: string\n  dynamic?: boolean\n}")
		assertContains(t, got, "    { label: '건물 목록', href: '/buildings' },\n")
		assertContains(t, got, "    { label: '건물 상세', dynamic: true },\n")
	})

	t.Run("dynamic false keeps the Phase004 bytes — no dynamic vocabulary", func(t *testing.T) {
		got := renderBreadcrumbsTS(trails, false)
		assertNotContains(t, got, "dynamic")
	})
}
