//ff:func feature=gen-react type=generator control=sequence
//ff:what renderDynamicBreadcrumbComponent — 동적 라벨 prop 을 받는 <Breadcrumb> 변형 TSX 소스 (라벨 state 있으면 그것, 없으면 정적 폴백)

package react

// renderDynamicBreadcrumbComponent returns the data-crumb-field variant
// of the shared <Breadcrumb> component (plans/stml/sitemap Phase006): the
// optional label prop carries the layout's crumb-label state, and a
// dynamic crumb renders it when set — falling back to the static label
// otherwise (fetch in flight, failed, or no state). This is the single
// fallback point, so the crumb never blanks or flickers. Selection
// between this and the static Phase004 form is renderBreadcrumbComponent's
// judgment.
func renderDynamicBreadcrumbComponent() string {
	return `// Generated by yongol. Do not edit.
import { Link, matchPath, useLocation } from 'react-router-dom'
import { BREADCRUMBS, BREADCRUMB_ROUTES } from '@/lib/breadcrumbs'

export function Breadcrumb({ label }: { label?: string | null }) {
  const { pathname } = useLocation()
  const route = BREADCRUMB_ROUTES.find((r) => matchPath(r.pattern, pathname))
  const trail = route ? BREADCRUMBS[route.page] : undefined
  if (!trail || trail.length < 2) return null
  return (
    <nav aria-label="Breadcrumb">
      <ol>
        {trail.map((crumb, i) => (
          <li key={i}>{crumb.href ? <Link to={crumb.href}>{crumb.label}</Link> : <span>{crumb.dynamic && label != null ? label : crumb.label}</span>}</li>
        ))}
      </ol>
    </nav>
  )
}
`
}
