//ff:func feature=gen-react type=generator control=sequence
//ff:what renderBreadcrumbComponent — 공용 <Breadcrumb> 컴포넌트 TSX 소스 (현재 라우트→trail 선택, 1조각 trail 비렌더, dynamic 시 라벨 prop + 정적 폴백)

package react

// renderBreadcrumbComponent returns the shared <Breadcrumb> component
// emitted to src/components/ui/Breadcrumb.tsx (plans/stml/sitemap
// Phase004 — the generator-owned ui/ subtree, never the user-authored
// components/ space). It matches the current pathname against the
// BREADCRUMB_ROUTES table (matchPath — first match after the
// specificity sort) and renders the selected trail above the layout's
// Outlet: crumbs with an href become <Link>, label-only crumbs <span>.
// No match (sitemap-unlisted page) and single-crumb trails (depth-1
// pages, defensive — the table already omits them) render nothing.
// dynamic (Phase006 — the sitemap declares some data-crumb-field)
// switches to the renderDynamicBreadcrumbComponent variant (optional
// label prop + static fallback); false keeps the Phase004 bytes
// identical.
func renderBreadcrumbComponent(dynamic bool) string {
	if dynamic {
		return renderDynamicBreadcrumbComponent()
	}
	return `// Generated by yongol. Do not edit.
import { Link, matchPath, useLocation } from 'react-router-dom'
import { BREADCRUMBS, BREADCRUMB_ROUTES } from '@/lib/breadcrumbs'

export function Breadcrumb() {
  const { pathname } = useLocation()
  const route = BREADCRUMB_ROUTES.find((r) => matchPath(r.pattern, pathname))
  const trail = route ? BREADCRUMBS[route.page] : undefined
  if (!trail || trail.length < 2) return null
  return (
    <nav aria-label="Breadcrumb">
      <ol>
        {trail.map((crumb, i) => (
          <li key={i}>{crumb.href ? <Link to={crumb.href}>{crumb.label}</Link> : <span>{crumb.label}</span>}</li>
        ))}
      </ol>
    </nav>
  )
}
`
}
