//ff:func feature=gen-react type=generator control=sequence
//ff:what writeTailwindConfig — tailwind.config.js / postcss.config.js / index.css 방출 (manifest.theme + DESIGN.md 토큰 반영)

package react

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/park-jun-woo/yongol/pkg/parser/design"
	"github.com/park-jun-woo/yongol/pkg/parser/manifest"
)

// writeTailwindConfig emits tailwind.config.js and postcss.config.js.
// When a DesignSpec is provided, its colors, rounded, and spacing tokens
// are merged into theme.extend. Manifest theme values take precedence for
// the shadcn semantic color slots; DesignSpec colors fill any remaining
// custom tokens. When neither source is present, shadcn defaults are used.
func writeTailwindConfig(frontendDir string, theme *manifest.FrontendTheme, dspec *design.DesignSpec) error {
	var b strings.Builder
	b.WriteString("// Generated by yongol. Customize via manifest.yaml frontend.theme or DESIGN.md.\n")
	b.WriteString("/** @type {import('tailwindcss').Config} */\n")
	b.WriteString("module.exports = {\n")
	b.WriteString("  content: ['./index.html', './src/**/*.{ts,tsx}'],\n")
	b.WriteString("  darkMode: 'class',\n")
	b.WriteString("  theme: {\n")
	b.WriteString("    extend: {\n")

	// --- colors ---
	b.WriteString("      colors: {\n")
	writeColorToken(&b, "primary", orDefault(theme, pickPrimary, designColor(dspec, "primary", "#0f172a")), designColor(dspec, "primary-foreground", "#f8fafc"))
	writeColorToken(&b, "secondary", orDefault(theme, pickSecondary, designColor(dspec, "secondary", "#f1f5f9")), designColor(dspec, "secondary-foreground", "#0f172a"))
	writeColorToken(&b, "accent", orDefault(theme, pickAccent, designColor(dspec, "accent", "#f1f5f9")), designColor(dspec, "accent-foreground", "#0f172a"))
	writeColorToken(&b, "destructive", orDefault(theme, pickDestructive, designColor(dspec, "destructive", "#ef4444")), designColor(dspec, "destructive-foreground", "#f8fafc"))
	writeColorToken(&b, "muted", orDefault(theme, pickMuted, designColor(dspec, "muted", "#f1f5f9")), designColor(dspec, "muted-foreground", "#64748b"))
	b.WriteString(fmt.Sprintf("        background: '%s',\n", orDefault(theme, pickBackground, designColor(dspec, "background", "#ffffff"))))
	b.WriteString(fmt.Sprintf("        foreground: '%s',\n", orDefault(theme, pickForeground, designColor(dspec, "foreground", "#0f172a"))))
	b.WriteString(fmt.Sprintf("        border: '%s',\n", orDefault(theme, pickBorder, designColor(dspec, "border", "#e2e8f0"))))

	if dspec != nil {
		writeExtraDesignColors(&b, dspec.Colors)
	}

	b.WriteString("      },\n")

	// --- borderRadius ---
	writeTailwindBorderRadius(&b, theme, dspec)

	// --- spacing ---
	writeTailwindSpacing(&b, dspec)

	b.WriteString("    },\n")
	b.WriteString("  },\n")
	b.WriteString("  plugins: [],\n")
	b.WriteString("}\n")
	if err := os.WriteFile(filepath.Join(frontendDir, "tailwind.config.js"), []byte(b.String()), 0o644); err != nil {
		return err
	}

	postcss := `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
	if err := os.WriteFile(filepath.Join(frontendDir, "postcss.config.cjs"), []byte(postcss), 0o644); err != nil {
		return err
	}

	index := `@tailwind base;
@tailwind components;
@tailwind utilities;
`
	return os.WriteFile(filepath.Join(frontendDir, "src", "index.css"), []byte(index), 0o644)
}
