//ff:func feature=gen-react type=generator control=sequence
//ff:what writeTailwindConfig — tailwind.config.js / postcss.config.js / index.css 방출 (manifest.theme 반영)

package react

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/park-jun-woo/yongol/pkg/parser/manifest"
)

// writeTailwindConfig emits tailwind.config.js and postcss.config.js.
// The color tokens follow shadcn/ui conventions; unset manifest fields
// inherit shadcn defaults. darkMode: 'class' is always enabled so users
// can opt in without re-configuring.
func writeTailwindConfig(frontendDir string, theme *manifest.FrontendTheme) error {
	var b strings.Builder
	b.WriteString("// Generated by yongol. Customize via manifest.yaml frontend.theme.\n")
	b.WriteString("/** @type {import('tailwindcss').Config} */\n")
	b.WriteString("module.exports = {\n")
	b.WriteString("  content: ['./index.html', './src/**/*.{ts,tsx}'],\n")
	b.WriteString("  darkMode: 'class',\n")
	b.WriteString("  theme: {\n")
	b.WriteString("    extend: {\n")
	b.WriteString("      colors: {\n")
	writeColorToken(&b, "primary", orDefault(theme, pickPrimary, "#0f172a"), "#f8fafc")
	writeColorToken(&b, "secondary", orDefault(theme, pickSecondary, "#f1f5f9"), "#0f172a")
	writeColorToken(&b, "accent", orDefault(theme, pickAccent, "#f1f5f9"), "#0f172a")
	writeColorToken(&b, "destructive", orDefault(theme, pickDestructive, "#ef4444"), "#f8fafc")
	writeColorToken(&b, "muted", orDefault(theme, pickMuted, "#f1f5f9"), "#64748b")
	b.WriteString(fmt.Sprintf("        background: '%s',\n", orDefault(theme, pickBackground, "#ffffff")))
	b.WriteString(fmt.Sprintf("        foreground: '%s',\n", orDefault(theme, pickForeground, "#0f172a")))
	b.WriteString(fmt.Sprintf("        border: '%s',\n", orDefault(theme, pickBorder, "#e2e8f0")))
	b.WriteString("      },\n")
	b.WriteString("      borderRadius: {\n")
	b.WriteString(fmt.Sprintf("        lg: '%s',\n", orDefault(theme, pickRadius, "0.5rem")))
	b.WriteString("        md: 'calc(var(--radius, 0.5rem) - 2px)',\n")
	b.WriteString("        sm: 'calc(var(--radius, 0.5rem) - 4px)',\n")
	b.WriteString("      },\n")
	b.WriteString("    },\n")
	b.WriteString("  },\n")
	b.WriteString("  plugins: [],\n")
	b.WriteString("}\n")
	if err := os.WriteFile(filepath.Join(frontendDir, "tailwind.config.js"), []byte(b.String()), 0o644); err != nil {
		return err
	}

	postcss := `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
	if err := os.WriteFile(filepath.Join(frontendDir, "postcss.config.js"), []byte(postcss), 0o644); err != nil {
		return err
	}

	index := `@tailwind base;
@tailwind components;
@tailwind utilities;
`
	return os.WriteFile(filepath.Join(frontendDir, "src", "index.css"), []byte(index), 0o644)
}
