//ff:func feature=gen-react type=generator control=sequence
//ff:what writeTailwindConfig — tailwind.config.js / postcss.config.js / index.css 방출 (manifest.theme + DESIGN.md 토큰 반영)

package react

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/park-jun-woo/yongol/pkg/parser/design"
	"github.com/park-jun-woo/yongol/pkg/parser/manifest"
)

// writeTailwindConfig emits tailwind.config.js and postcss.config.js.
// When a DesignSpec is provided, its colors, rounded, and spacing tokens
// are merged into theme.extend. Manifest theme values take precedence for
// the shadcn semantic color slots; DesignSpec colors fill any remaining
// custom tokens. When neither source is present, shadcn defaults are used.
func writeTailwindConfig(frontendDir string, theme *manifest.FrontendTheme, dspec *design.DesignSpec) error {
	var b strings.Builder
	b.WriteString("// Generated by yongol. Customize via manifest.yaml frontend.theme or DESIGN.md.\n")
	b.WriteString("/** @type {import('tailwindcss').Config} */\n")
	b.WriteString("module.exports = {\n")
	b.WriteString("  content: ['./index.html', './src/**/*.{ts,tsx}'],\n")
	b.WriteString("  darkMode: 'class',\n")
	b.WriteString("  theme: {\n")
	b.WriteString("    extend: {\n")

	// --- colors ---
	b.WriteString("      colors: {\n")
	writeColorToken(&b, "primary", orDefault(theme, pickPrimary, designColor(dspec, "primary", "#0f172a")), designColor(dspec, "primary-foreground", "#f8fafc"))
	writeColorToken(&b, "secondary", orDefault(theme, pickSecondary, designColor(dspec, "secondary", "#f1f5f9")), designColor(dspec, "secondary-foreground", "#0f172a"))
	writeColorToken(&b, "accent", orDefault(theme, pickAccent, designColor(dspec, "accent", "#f1f5f9")), designColor(dspec, "accent-foreground", "#0f172a"))
	writeColorToken(&b, "destructive", orDefault(theme, pickDestructive, designColor(dspec, "destructive", "#ef4444")), designColor(dspec, "destructive-foreground", "#f8fafc"))
	writeColorToken(&b, "muted", orDefault(theme, pickMuted, designColor(dspec, "muted", "#f1f5f9")), designColor(dspec, "muted-foreground", "#64748b"))
	b.WriteString(fmt.Sprintf("        background: '%s',\n", orDefault(theme, pickBackground, designColor(dspec, "background", "#ffffff"))))
	b.WriteString(fmt.Sprintf("        foreground: '%s',\n", orDefault(theme, pickForeground, designColor(dspec, "foreground", "#0f172a"))))
	b.WriteString(fmt.Sprintf("        border: '%s',\n", orDefault(theme, pickBorder, designColor(dspec, "border", "#e2e8f0"))))

	// Extra DESIGN.md colors not covered by the semantic slots above.
	if dspec != nil {
		writeExtraDesignColors(&b, dspec.Colors)
	}

	b.WriteString("      },\n")

	// --- borderRadius ---
	b.WriteString("      borderRadius: {\n")
	if dspec != nil && len(dspec.Rounded) > 0 {
		keys := sortedMapKeys(dspec.Rounded)
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("        %s: '%s',\n", k, dspec.Rounded[k]))
		}
	} else {
		b.WriteString(fmt.Sprintf("        lg: '%s',\n", orDefault(theme, pickRadius, "0.5rem")))
		b.WriteString("        md: 'calc(var(--radius, 0.5rem) - 2px)',\n")
		b.WriteString("        sm: 'calc(var(--radius, 0.5rem) - 4px)',\n")
	}
	b.WriteString("      },\n")

	// --- spacing ---
	if dspec != nil && len(dspec.Spacing) > 0 {
		b.WriteString("      spacing: {\n")
		keys := sortedMapKeys(dspec.Spacing)
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("        %s: '%s',\n", k, dspec.Spacing[k]))
		}
		b.WriteString("      },\n")
	}

	b.WriteString("    },\n")
	b.WriteString("  },\n")
	b.WriteString("  plugins: [],\n")
	b.WriteString("}\n")
	if err := os.WriteFile(filepath.Join(frontendDir, "tailwind.config.js"), []byte(b.String()), 0o644); err != nil {
		return err
	}

	postcss := `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
	if err := os.WriteFile(filepath.Join(frontendDir, "postcss.config.js"), []byte(postcss), 0o644); err != nil {
		return err
	}

	index := `@tailwind base;
@tailwind components;
@tailwind utilities;
`
	return os.WriteFile(filepath.Join(frontendDir, "src", "index.css"), []byte(index), 0o644)
}

// semanticColorNames lists the DESIGN.md color keys that are already handled
// by the fixed semantic slots (primary, secondary, accent, destructive,
// muted, background, foreground, border) and their -foreground variants.
var semanticColorNames = map[string]bool{
	"primary":               true,
	"primary-foreground":    true,
	"secondary":             true,
	"secondary-foreground":  true,
	"accent":                true,
	"accent-foreground":     true,
	"destructive":           true,
	"destructive-foreground": true,
	"muted":                 true,
	"muted-foreground":      true,
	"background":            true,
	"foreground":            true,
	"border":                true,
}

// writeExtraDesignColors emits DESIGN.md color tokens not already covered
// by the semantic slots.
func writeExtraDesignColors(b *strings.Builder, colors map[string]string) {
	keys := sortedMapKeys(colors)
	for _, k := range keys {
		if semanticColorNames[k] {
			continue
		}
		b.WriteString(fmt.Sprintf("        '%s': '%s',\n", k, colors[k]))
	}
}

// designColor returns the DESIGN.md color value for a key, falling back to def.
func designColor(dspec *design.DesignSpec, key, def string) string {
	if dspec == nil || dspec.Colors == nil {
		return def
	}
	if v, ok := dspec.Colors[key]; ok {
		return v
	}
	return def
}

// sortedMapKeys returns the keys of a string map in sorted order.
func sortedMapKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
