//ff:func feature=gen-react type=generator control=iteration dimension=1
//ff:what writeAPIClient — src/lib/api.ts 에 operationId 기반 api 객체 방출 (bearer/cookie 모드 분기)

package react

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// writeAPIClient emits src/lib/api.ts shaped as
//
//	export const api = {
//	  <OperationID>: (args: Req<'OperationID'>) => client.METHOD(path, { ... } as any).then(r => r.data as Res<'OperationID'>),
//	  ...
//	}
//
// The object key matches the OpenAPI operationId exactly (PascalCase or
// camelCase — preserved). This is the contract XOT-1 checks against at
// validate time.
//
// plan selects the auth mode wiring (Phase004):
//   - bearer: Bearer-injection middleware reading the session store. With
//     plan.refresh, 401s go through the single-flight refresh + retry-once
//     wrapper (withAuthRetry) instead of the immediate clear+/login.
//   - cookie/hybrid: createClient gets credentials: 'include' and, when
//     plan.csrf, the double-submit CSRF header middleware. No store, no
//     Bearer, no refresh flow.
func writeAPIClient(srcDir string, doc *openapi3.T, plan apiClientPlan) error {
	if err := os.MkdirAll(filepath.Join(srcDir, "lib"), 0o755); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Generated by yongol. Do not edit.\n")
	b.WriteString("// Source of truth: specs/api/openapi.yaml (operationId-keyed).\n")
	b.WriteString("import createClient from 'openapi-fetch'\n")
	b.WriteString("import type { paths, operations } from '../types/api'\n")
	if plan.bearer {
		b.WriteString("import { useAuthStore } from '../stores/auth'\n")
	}
	b.WriteString("\n")
	writeReqResTypes(&b)

	// baseUrl is intentionally empty: OpenAPI path keys already carry the
	// '/api' prefix, so a non-empty baseUrl here would double-prefix the
	// request URL ('/api' + '/api/...' = '/api/api/...'). See BUG-110.
	const baseURL = ""
	var paths []string
	if doc != nil && doc.Paths != nil {
		for path := range doc.Paths.Map() {
			paths = append(paths, path)
		}
	}
	if err := detectDoublePrefix(baseURL, paths); err != nil {
		return err
	}
	clientInit := "{ baseUrl: '" + baseURL + "' }"
	if plan.cookie {
		// httpOnly session cookies must travel with every request.
		clientInit = "{ baseUrl: '" + baseURL + "', credentials: 'include' }"
	}
	b.WriteString("const client = createClient<paths>(" + clientInit + ")\n")

	withRetry := plan.bearer && plan.refresh != nil
	if plan.bearer {
		writeAuthzMiddleware(&b, withRetry)
		if withRetry {
			writeRefreshFlow(&b, plan.refresh)
		}
	}
	if plan.cookie && plan.csrf {
		writeCSRFMiddleware(&b, plan.csrfCookieName, plan.csrfHeaderName)
	}
	if plan.cookie {
		writeCookie401Redirect(&b)
	}

	b.WriteString("\n")

	if doc == nil || doc.Paths == nil {
		b.WriteString("export const api = {}\n")
		return os.WriteFile(filepath.Join(srcDir, "lib", "api.ts"), []byte(b.String()), 0644)
	}

	entries := collectEndpoints(doc)
	sort.Slice(entries, func(i, j int) bool { return entries[i].opID < entries[j].opID })

	b.WriteString("export const api = {\n")
	for _, ep := range entries {
		writeApiClientEntry(&b, ep, withRetry)
	}
	b.WriteString("}\n")

	return os.WriteFile(filepath.Join(srcDir, "lib", "api.ts"), []byte(b.String()), 0644)
}
