//ff:func feature=gen-react type=generator control=sequence
//ff:what src/stores/auth.ts — claims 캡처 존재 시 claims 포함 store 방출 (bearer 전체형 / cookie claims 전용형)

package react

import (
	"os"
	"path/filepath"
)

// writeSessionStoreClaims emits src/stores/auth.ts for projects with at
// least one auth.claims.* capture (plans/stml/sitemap Phase005). tokens
// selects the shape: true (bearer mode) keeps the token field and the
// setAuth contract of writeSessionStore byte-for-byte — setAuth never
// touches claims, so the 401 refresh flow (write_refresh_flow.go) preserves
// them — and adds claims/setClaim, with clear() resetting claims too;
// hasRefresh (resolveHasRefresh) gates the refresh field/argument exactly as
// writeSessionStore does (BUG-135). false (cookie mode — httpOnly cookies
// hold the tokens) emits the claims-only reduced store (no token, no
// refresh, no setAuth). store
// selects persistence exactly like writeSessionStore: "localStorage" wraps
// in zustand persist, anything else stays in memory. Projects without a
// claims capture keep writeSessionStore so their output stays
// byte-identical.
func writeSessionStoreClaims(srcDir, store string, tokens, hasRefresh bool) error {
	dir := filepath.Join(srcDir, "stores")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	const header = `// Generated by yongol. Do not edit.
import { create } from 'zustand'
`
	types := claimsStoreTypes(tokens, hasRefresh)
	body := claimsStoreBody(tokens, hasRefresh)

	src := header + types + "export const useAuthStore = create<AuthState>()((set) => ({\n" +
		indentLines(body, "  ") + "}))\n"
	if store == "localStorage" {
		src = header + "import { persist } from 'zustand/middleware'\n" + types +
			"export const useAuthStore = create<AuthState>()(\n" +
			"  persist(\n" +
			"    (set) => ({\n" +
			indentLines(body, "      ") +
			"    }),\n" +
			"    { name: 'auth' },\n" +
			"  ),\n" +
			")\n"
	}
	return os.WriteFile(filepath.Join(dir, "auth.ts"), []byte(src), 0o644)
}
