//ff:func feature=gen-react type=generator control=sequence
//ff:what src/stores/auth.ts — bearer 세션 store(zustand) 방출, localStorage면 persist 래핑, hasRefresh로 refresh 필드 게이트

package react

import (
	"os"
	"path/filepath"
)

// writeSessionStore emits src/stores/auth.ts, the single session store both
// the page mutations (data-capture commits) and the API client interceptor
// (Bearer injection) read. store selects persistence per
// frontend.auth.ResolvedStore(): "localStorage" wraps the store in zustand
// persist; "memory" keeps it non-persistent (lost on reload by design).
// hasRefresh (resolveHasRefresh) gates the refresh token field/argument:
// false drops the dead refresh surface (BUG-135); true is byte-identical to
// the pre-BUG-135 output.
func writeSessionStore(srcDir, store string, hasRefresh bool) error {
	dir := filepath.Join(srcDir, "stores")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	const header = `// Generated by yongol. Do not edit.
import { create } from 'zustand'
`
	types := sessionStoreTypes(hasRefresh)
	body := sessionStoreBody(hasRefresh)

	src := header + types + "export const useAuthStore = create<AuthState>()((set) => ({\n" +
		indentLines(body, "  ") + "}))\n"
	if store == "localStorage" {
		src = header + "import { persist } from 'zustand/middleware'\n" + types +
			"export const useAuthStore = create<AuthState>()(\n" +
			"  persist(\n" +
			"    (set) => ({\n" +
			indentLines(body, "      ") +
			"    }),\n" +
			"    { name: 'auth' },\n" +
			"  ),\n" +
			")\n"
	}
	return os.WriteFile(filepath.Join(dir, "auth.ts"), []byte(src), 0o644)
}
