//ff:func feature=gen-react type=generator control=sequence
//ff:what src/stores/auth.ts — bearer 세션 store(zustand) 방출, localStorage면 persist 래핑

package react

import (
	"os"
	"path/filepath"
)

// writeSessionStore emits src/stores/auth.ts, the single session store both
// the page mutations (data-capture commits) and the API client interceptor
// (Bearer injection) read. store selects persistence per
// frontend.auth.ResolvedStore(): "localStorage" wraps the store in zustand
// persist; "memory" keeps it non-persistent (lost on reload by design).
func writeSessionStore(srcDir, store string) error {
	dir := filepath.Join(srcDir, "stores")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	const header = `// Generated by yongol. Do not edit.
import { create } from 'zustand'
`
	const types = `
interface AuthState {
  token: string | null
  refresh: string | null
  setAuth: (token?: string | null, refresh?: string | null) => void
  clear: () => void
}

`
	const persistStore = `import { persist } from 'zustand/middleware'
` + types + `export const useAuthStore = create<AuthState>()(
  persist(
    (set) => ({
      token: null,
      refresh: null,
      setAuth: (token, refresh) =>
        set((state) => ({
          token: token ?? null,
          refresh: refresh === undefined ? state.refresh : refresh,
        })),
      clear: () => set({ token: null, refresh: null }),
    }),
    { name: 'auth' },
  ),
)
`
	const memoryStore = types + `export const useAuthStore = create<AuthState>()((set) => ({
  token: null,
  refresh: null,
  setAuth: (token, refresh) =>
    set((state) => ({
      token: token ?? null,
      refresh: refresh === undefined ? state.refresh : refresh,
    })),
  clear: () => set({ token: null, refresh: null }),
}))
`

	src := header + memoryStore
	if store == "localStorage" {
		src = header + persistStore
	}
	return os.WriteFile(filepath.Join(dir, "auth.ts"), []byte(src), 0o644)
}
