//ff:func feature=gen-react type=generator control=sequence
//ff:what writeReqResTypes — Req<K> / Res<K> 타입 헬퍼를 방출한다

package react

import "strings"

// writeReqResTypes emits the Req<K> and Res<K> conditional type helpers that
// extract request-body (or query-params for GET) and 200-response types from
// the operations map generated by openapi-typescript.
func writeReqResTypes(b *strings.Builder) {
	b.WriteString("type Req<K extends keyof operations> =\n")
	b.WriteString("  operations[K] extends { requestBody: { content: { 'application/json': infer B } } } ? B :\n")
	b.WriteString("  operations[K] extends { parameters: { query?: infer Q } } ? Q :\n")
	b.WriteString("  void\n\n")

	b.WriteString("type Res<K extends keyof operations> =\n")
	b.WriteString("  operations[K] extends { responses: { 200: { content: { 'application/json': infer R } } } } ? R : void\n\n")
}
