//ff:func feature=gen-react type=generator control=iteration dimension=1
//ff:what writeAPIClient — src/api.ts 에 operationId 기반 apiClient 객체 방출

package react

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// writeAPIClient emits src/api.ts shaped as
//
//	export const apiClient = {
//	  <OperationID>: (args?: {...}) => client.METHOD(path, { ... }).then(r => r.data),
//	  ...
//	}
//
// The object key matches the OpenAPI operationId exactly (PascalCase or
// camelCase — preserved). This is the contract XOT-1 checks against at
// validate time.
func writeAPIClient(srcDir string, doc *openapi3.T) error {
	var b strings.Builder
	b.WriteString("// Generated by yongol. Do not edit.\n")
	b.WriteString("// Source of truth: specs/api/openapi.yaml (operationId-keyed).\n")
	b.WriteString("import createClient from 'openapi-fetch'\n")
	b.WriteString("import type { paths } from './types/api'\n\n")
	b.WriteString("const client = createClient<paths>({ baseUrl: '/api' })\n\n")

	if doc == nil || doc.Paths == nil {
		b.WriteString("export const apiClient = {}\n")
		return os.WriteFile(filepath.Join(srcDir, "api.ts"), []byte(b.String()), 0644)
	}

	entries := collectEndpoints(doc)
	sort.Slice(entries, func(i, j int) bool { return entries[i].opID < entries[j].opID })

	b.WriteString("export const apiClient = {\n")
	for _, ep := range entries {
		writeApiClientEntry(&b, ep)
	}
	b.WriteString("}\n")

	return os.WriteFile(filepath.Join(srcDir, "api.ts"), []byte(b.String()), 0644)
}
