-- YONGOL_SCHEMA_HASH: 935666a7aed118ebc691e83a4d3ecaec24f38b45abb6748d60ddaf908223f3bf
-- Generated by yongol v0.2.2 at 2026-04-23T00:28:11Z

CREATE TABLE actions (
    id BIGINT NOT NULL DEFAULT nextval('actions_id_seq'),
    workflow_id BIGINT NOT NULL,
    action_type TEXT NOT NULL,
    payload_template JSONB NOT NULL DEFAULT '{}',
    sequence_order BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT actions_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows (id) ON DELETE CASCADE
);
CREATE INDEX idx_actions_workflow_id ON actions (workflow_id);


CREATE TABLE execution_logs (
    id BIGINT NOT NULL DEFAULT nextval('execution_logs_id_seq'),
    workflow_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    status TEXT NOT NULL,
    credits_spent BIGINT NOT NULL DEFAULT 0,
    executed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT execution_logs_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES workflows (id),
    CONSTRAINT execution_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id)
);
CREATE INDEX idx_execution_logs_org_id ON execution_logs (org_id);
CREATE INDEX idx_execution_logs_workflow_id ON execution_logs (workflow_id);


CREATE TABLE organizations (
    id BIGINT NOT NULL DEFAULT nextval('organizations_id_seq'),
    name TEXT NOT NULL,
    plan_type TEXT NOT NULL DEFAULT 'free',
    credits_balance BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT organizations_plan_type_check CHECK (plan_type IN ('free', 'pro', 'enterprise'))
);


CREATE TABLE users (
    id BIGINT NOT NULL DEFAULT nextval('users_id_seq'),
    org_id BIGINT NOT NULL,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id),
    CONSTRAINT users_role_check CHECK (role IN ('admin', 'member'))
);
CREATE INDEX idx_users_org_id ON users (org_id);
CREATE UNIQUE INDEX users_email_key ON users (email);


CREATE TABLE workflows (
    id BIGINT NOT NULL DEFAULT nextval('workflows_id_seq'),
    org_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    trigger_event TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT workflows_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations (id),
    CONSTRAINT workflows_status_check CHECK (status IN ('draft', 'active', 'paused', 'archived'))
);
CREATE INDEX idx_workflows_org_id ON workflows (org_id);

