// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

//ff:type feature=db type=model
//ff:what ActionCopyToWorkflowParams
package db

type ActionCopyToWorkflowParams struct {
	TargetWorkflowID int64
	SourceWorkflowID int64
}
