// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

//ff:func feature=db type=model control=sequence
//ff:what actionListByWorkflowID
package db

const actionListByWorkflowID = `-- name: ActionListByWorkflowID :many
SELECT id, workflow_id, action_type, config, sequence_order FROM actions WHERE workflow_id = $1 ORDER BY sequence_order ASC
LIMIT 1000
`
