// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what Action
package db

type Action struct {
	ID            int64
	WorkflowID    int64
	ActionType    string
	Config        string
	SequenceOrder int64
}
