// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

//ff:func feature=db type=model control=sequence
//ff:what actionCopyToWorkflow
package db

const actionCopyToWorkflow = `-- name: ActionCopyToWorkflow :exec
INSERT INTO actions (workflow_id, action_type, config, sequence_order)
SELECT $1, a.action_type, a.config, a.sequence_order FROM actions a WHERE a.workflow_id = $2
`
