// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

//ff:type feature=db type=model
//ff:what ActionCreateParams
package db

type ActionCreateParams struct {
	WorkflowID    int64
	ActionType    string
	Config        string
	SequenceOrder int64
}
