// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:type feature=db type=model
//ff:what AuditLogCountByOrgIDFilteredParams
package db

type AuditLogCountByOrgIDFilteredParams struct {
	OrgID        int64
	FilterAction string
}
