// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:type feature=db type=model
//ff:what AuditLogCreateParams
package db

type AuditLogCreateParams struct {
	OrgID        int64
	ActorID      int64
	Action       string
	ResourceType string
	ResourceID   int64
	Detail       string
}
