// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:func feature=db type=model control=sequence
//ff:what auditLogCreate
package db

const auditLogCreate = `-- name: AuditLogCreate :exec
INSERT INTO audit_logs (org_id, actor_id, action, resource_type, resource_id, detail)
VALUES ($1, $2, $3, $4, $5, $6)
`
