// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:type feature=db type=model
//ff:what AuditLogListByOrgIDPagedParams
package db

type AuditLogListByOrgIDPagedParams struct {
	OrgID        int64
	FilterAction string
	SortBy       interface{}
	SortDir      interface{}
	Page         interface{}
	PerPage      int32
}
