// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:func feature=db type=model control=sequence
//ff:what auditLogFindByID
package db

const auditLogFindByID = `-- name: AuditLogFindByID :one
SELECT id, org_id, actor_id, action, resource_type, resource_id, detail, created_at FROM audit_logs WHERE id = $1
`
