// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:func feature=db type=model control=sequence
//ff:what auditLogCountByOrgIDFiltered
package db

const auditLogCountByOrgIDFiltered = `-- name: AuditLogCountByOrgIDFiltered :one
SELECT COUNT(*) FROM audit_logs
WHERE org_id = $1
  AND ($2::varchar = '' OR action = $2)
`
