// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:func feature=db type=model control=sequence
//ff:what auditLogListByOrgIDPaged
package db

const auditLogListByOrgIDPaged = `-- name: AuditLogListByOrgIDPaged :many
SELECT id, org_id, actor_id, action, resource_type, resource_id, detail, created_at FROM audit_logs
WHERE org_id = $1
  AND ($2::varchar = '' OR action = $2)
ORDER BY
  CASE WHEN $3 = 'created_at' AND $4 = 'asc'  THEN created_at END ASC,
  CASE WHEN $3 = 'created_at' AND $4 = 'desc' THEN created_at END DESC,
  CASE WHEN $3 = 'action' AND $4 = 'asc'  THEN action END ASC,
  CASE WHEN $3 = 'action' AND $4 = 'desc' THEN action END DESC
LIMIT $6 OFFSET ($5 - 1) * $6
`
