// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what AuditLog
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           int64
	OrgID        int64
	ActorID      int64
	Action       string
	ResourceType string
	ResourceID   int64
	Detail       string
	CreatedAt    pgtype.Timestamptz
}
