// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

//ff:type feature=db type=model
//ff:what ExecutionLogCreateParams
package db

type ExecutionLogCreateParams struct {
	WorkflowID   int64
	OrgID        int64
	Status       string
	CreditsSpent int64
}
