// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

//ff:func feature=db type=model control=sequence
//ff:what executionLogListByWorkflowID
package db

const executionLogListByWorkflowID = `-- name: ExecutionLogListByWorkflowID :many
SELECT id, workflow_id, org_id, status, credits_spent, executed_at FROM execution_logs WHERE workflow_id = $1 ORDER BY executed_at DESC
LIMIT 1000
`
