// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

//ff:func feature=db type=model control=sequence
//ff:what loginLookup
package db

const loginLookup = `-- name: LoginLookup :one
SELECT id, password_hash, jsonb_build_object('ID', id, 'Email', email, 'Role', role, 'OrgID', org_id) AS claims FROM users WHERE email = $1
`
