// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

//ff:type feature=db type=model
//ff:what LoginLookupRow
package db

type LoginLookupRow struct {
	ID           int64
	PasswordHash string
	Claims       []byte
}
