// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:func feature=db type=model control=sequence
//ff:what organizationFindByID
package db

const organizationFindByID = `-- name: OrganizationFindByID :one
SELECT id, name, plan_type, credits_balance, created_at FROM organizations WHERE id = $1
`
