// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what Organization
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID             int64
	Name           string
	PlanType       string
	CreditsBalance int64
	CreatedAt      pgtype.Timestamptz
}
