// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:type feature=db type=model
//ff:what OrganizationDeductCreditsParams
package db

type OrganizationDeductCreditsParams struct {
	Amount int64
	ID     int64
}
