// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=model control=sequence
//ff:what ownerLookupWebhook
package db

const ownerLookupWebhook = `-- name: OwnerLookupWebhook :one
SELECT org_id FROM webhooks WHERE id = $1
`
