// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what ownerLookupWorkflow
package db

const ownerLookupWorkflow = `-- name: OwnerLookupWorkflow :one
SELECT org_id FROM workflows WHERE id = $1
`
