// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:func feature=db type=query control=iteration dimension=1
//ff:what Queries.TemplateListCursor
//ff:checked llm=yongol-gen hash=0dc09c84
package db

import (
	"context"
)

func (q *Queries) TemplateListCursor(ctx context.Context, arg TemplateListCursorParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, templateListCursor, arg.Cursor, arg.FilterCategory, arg.PerPage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.SourceWorkflowID,
			&i.OrgID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CloneCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
