// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.WebhookCreate
//ff:checked llm=yongol-gen hash=fa880484
package db

import (
	"context"
)

func (q *Queries) WebhookCreate(ctx context.Context, arg WebhookCreateParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, webhookCreate, arg.OrgID, arg.Url, arg.EventType)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.EventType,
		&i.CreatedAt,
	)
	return i, err
}
