// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:func feature=db type=query control=iteration dimension=1
//ff:what Queries.AuditLogListByOrgIDPaged
//ff:checked llm=yongol-gen hash=1fc34035
package db

import (
	"context"
)

func (q *Queries) AuditLogListByOrgIDPaged(ctx context.Context, arg AuditLogListByOrgIDPagedParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, auditLogListByOrgIDPaged,
		arg.OrgID,
		arg.FilterAction,
		arg.SortBy,
		arg.SortDir,
		arg.Page,
		arg.PerPage,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
