// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.ExecutionLogCreate
//ff:checked llm=yongol-gen hash=cab988ef
package db

import (
	"context"
)

func (q *Queries) ExecutionLogCreate(ctx context.Context, arg ExecutionLogCreateParams) (ExecutionLog, error) {
	row := q.db.QueryRow(ctx, executionLogCreate,
		arg.WorkflowID,
		arg.OrgID,
		arg.Status,
		arg.CreditsSpent,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.CreditsSpent,
		&i.ExecutedAt,
	)
	return i, err
}
