// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.TemplateIncrementCloneCount
//ff:checked llm=yongol-gen hash=a0af7f54
package db

import (
	"context"
)

func (q *Queries) TemplateIncrementCloneCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, templateIncrementCloneCount, id)
	return err
}
