// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.OrganizationDeductCredits
//ff:checked llm=yongol-gen hash=c3c45967
package db

import (
	"context"
)

func (q *Queries) OrganizationDeductCredits(ctx context.Context, arg OrganizationDeductCreditsParams) error {
	_, err := q.db.Exec(ctx, organizationDeductCredits, arg.Amount, arg.ID)
	return err
}
