// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.WebhookFindByID
//ff:checked llm=yongol-gen hash=a0597f42
package db

import (
	"context"
)

func (q *Queries) WebhookFindByID(ctx context.Context, id int64) (Webhook, error) {
	row := q.db.QueryRow(ctx, webhookFindByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.EventType,
		&i.CreatedAt,
	)
	return i, err
}
