// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=iteration dimension=1
//ff:what Queries.WorkflowListVersions
//ff:checked llm=yongol-gen hash=db67d176
package db

import (
	"context"
)

func (q *Queries) WorkflowListVersions(ctx context.Context, arg WorkflowListVersionsParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, workflowListVersions, arg.RootID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.TriggerEvent,
			&i.Status,
			&i.Version,
			&i.RootWorkflowID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
