// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.OwnerLookupWorkflow
//ff:checked llm=yongol-gen hash=88cd1de7
package db

import (
	"context"
)

func (q *Queries) OwnerLookupWorkflow(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, ownerLookupWorkflow, id)
	var org_id int64
	err := row.Scan(&org_id)
	return org_id, err
}
