// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=query control=iteration dimension=1
//ff:what Queries.WebhookListByOrgID
//ff:checked llm=yongol-gen hash=b532bb15
package db

import (
	"context"
)

func (q *Queries) WebhookListByOrgID(ctx context.Context, orgID int64) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, webhookListByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
