// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.ActionCopyToWorkflow
//ff:checked llm=yongol-gen hash=4eb7815b
package db

import (
	"context"
)

func (q *Queries) ActionCopyToWorkflow(ctx context.Context, arg ActionCopyToWorkflowParams) error {
	_, err := q.db.Exec(ctx, actionCopyToWorkflow, arg.TargetWorkflowID, arg.SourceWorkflowID)
	return err
}
