// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

//ff:func feature=db type=query control=iteration dimension=1
//ff:what Queries.ActionListByWorkflowID
//ff:checked llm=yongol-gen hash=00f102b5
package db

import (
	"context"
)

func (q *Queries) ActionListByWorkflowID(ctx context.Context, workflowID int64) ([]Action, error) {
	rows, err := q.db.Query(ctx, actionListByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.ActionType,
			&i.Config,
			&i.SequenceOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
