// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.AuditLogCountByOrgIDFiltered
//ff:checked llm=yongol-gen hash=ce29185e
package db

import (
	"context"
)

func (q *Queries) AuditLogCountByOrgIDFiltered(ctx context.Context, arg AuditLogCountByOrgIDFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, auditLogCountByOrgIDFiltered, arg.OrgID, arg.FilterAction)
	var count int64
	err := row.Scan(&count)
	return count, err
}
