// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=iteration dimension=1
//ff:what Queries.WorkflowListByOrgID
//ff:checked llm=yongol-gen hash=1729612c
package db

import (
	"context"
)

func (q *Queries) WorkflowListByOrgID(ctx context.Context, orgID int64) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, workflowListByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.TriggerEvent,
			&i.Status,
			&i.Version,
			&i.RootWorkflowID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
