// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.TemplateFindByID
//ff:checked llm=yongol-gen hash=d8e5515b
package db

import (
	"context"
)

func (q *Queries) TemplateFindByID(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRow(ctx, templateFindByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.SourceWorkflowID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CloneCount,
		&i.CreatedAt,
	)
	return i, err
}
