// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.AuditLogFindByID
//ff:checked llm=yongol-gen hash=27da8489
package db

import (
	"context"
)

func (q *Queries) AuditLogFindByID(ctx context.Context, id int64) (AuditLog, error) {
	row := q.db.QueryRow(ctx, auditLogFindByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}
