// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.WorkflowCreateVersion
//ff:checked llm=yongol-gen hash=029ec603
package db

import (
	"context"
)

func (q *Queries) WorkflowCreateVersion(ctx context.Context, arg WorkflowCreateVersionParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, workflowCreateVersion,
		arg.OrgID,
		arg.Title,
		arg.TriggerEvent,
		arg.Version,
		arg.RootWorkflowID,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.TriggerEvent,
		&i.Status,
		&i.Version,
		&i.RootWorkflowID,
		&i.CreatedAt,
	)
	return i, err
}
