// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.WebhookDelete
//ff:checked llm=yongol-gen hash=8a05e800
package db

import (
	"context"
)

func (q *Queries) WebhookDelete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, webhookDelete, id)
	return err
}
