// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.AuditLogCreate
//ff:checked llm=yongol-gen hash=8bd6fd72
package db

import (
	"context"
)

func (q *Queries) AuditLogCreate(ctx context.Context, arg AuditLogCreateParams) error {
	_, err := q.db.Exec(ctx, auditLogCreate,
		arg.OrgID,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Detail,
	)
	return err
}
