// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.TemplateCreate
//ff:checked llm=yongol-gen hash=28f8a9a7
package db

import (
	"context"
)

func (q *Queries) TemplateCreate(ctx context.Context, arg TemplateCreateParams) (Template, error) {
	row := q.db.QueryRow(ctx, templateCreate,
		arg.SourceWorkflowID,
		arg.OrgID,
		arg.Title,
		arg.Description,
		arg.Category,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.SourceWorkflowID,
		&i.OrgID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CloneCount,
		&i.CreatedAt,
	)
	return i, err
}
