// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.LoginLookup
//ff:checked llm=yongol-gen hash=d4154602
package db

import (
	"context"
)

func (q *Queries) LoginLookup(ctx context.Context, email string) (LoginLookupRow, error) {
	row := q.db.QueryRow(ctx, loginLookup, email)
	var i LoginLookupRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.Claims)
	return i, err
}
