// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=query control=sequence
//ff:what Queries.OwnerLookupWebhook
//ff:checked llm=yongol-gen hash=824879be
package db

import (
	"context"
)

func (q *Queries) OwnerLookupWebhook(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, ownerLookupWebhook, id)
	var org_id int64
	err := row.Scan(&org_id)
	return org_id, err
}
