// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

//ff:func feature=db type=query control=iteration dimension=1
//ff:what Queries.ExecutionLogListByWorkflowID
//ff:checked llm=yongol-gen hash=488deb3d
package db

import (
	"context"
)

func (q *Queries) ExecutionLogListByWorkflowID(ctx context.Context, workflowID int64) ([]ExecutionLog, error) {
	rows, err := q.db.Query(ctx, executionLogListByWorkflowID, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionLog
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.OrgID,
			&i.Status,
			&i.CreditsSpent,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
