// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

//ff:func feature=db type=model control=sequence
//ff:what refreshTokenRevoke
package db

const refreshTokenRevoke = `-- name: RefreshTokenRevoke :exec
UPDATE refresh_tokens SET revoked_at = NOW()
WHERE token_hash = $1 AND revoked_at IS NULL
`
