// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what RefreshToken
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	TokenHash string
	Claims    []byte
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
