// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

//ff:type feature=db type=model
//ff:what RefreshTokenInsertParams
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshTokenInsertParams struct {
	TokenHash string
	Claims    []byte
	ExpiresAt pgtype.Timestamptz
}
