// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

//ff:func feature=db type=model control=sequence
//ff:what refreshTokenRevokeAll
package db

const refreshTokenRevokeAll = `-- name: RefreshTokenRevokeAll :exec
UPDATE refresh_tokens SET revoked_at = NOW()
WHERE revoked_at IS NULL AND claims @> $1
`
