// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

//ff:func feature=db type=model control=sequence
//ff:what refreshTokenFindByHash
package db

const refreshTokenFindByHash = `-- name: RefreshTokenFindByHash :one
SELECT claims, expires_at, revoked_at FROM refresh_tokens WHERE token_hash = $1
`
