// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:type feature=db type=model
//ff:what TemplateListCursorParams
package db

type TemplateListCursorParams struct {
	Cursor         int64
	FilterCategory string
	PerPage        int32
}
