// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:type feature=db type=model
//ff:what TemplateCreateParams
package db

type TemplateCreateParams struct {
	SourceWorkflowID int64
	OrgID            int64
	Title            string
	Description      string
	Category         string
}
