// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what Template
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Template struct {
	ID               int64
	SourceWorkflowID int64
	OrgID            int64
	Title            string
	Description      string
	Category         string
	CloneCount       int64
	CreatedAt        pgtype.Timestamptz
}
