// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:func feature=db type=model control=sequence
//ff:what templateListCursor
package db

const templateListCursor = `-- name: TemplateListCursor :many
SELECT id, source_workflow_id, org_id, title, description, category, clone_count, created_at FROM templates
WHERE ($1::bigint = 0 OR id < $1)
  AND ($2::varchar = '' OR category = $2)
ORDER BY id DESC
LIMIT $3
`
