// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:func feature=db type=model control=sequence
//ff:what templateIncrementCloneCount
package db

const templateIncrementCloneCount = `-- name: TemplateIncrementCloneCount :exec
UPDATE templates SET clone_count = clone_count + 1 WHERE id = $1
`
