// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:func feature=db type=model control=sequence
//ff:what templateCreate
package db

const templateCreate = `-- name: TemplateCreate :one
INSERT INTO templates (source_workflow_id, org_id, title, description, category)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, source_workflow_id, org_id, title, description, category, clone_count, created_at
`
