// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

//ff:func feature=db type=model control=sequence
//ff:what templateFindByID
package db

const templateFindByID = `-- name: TemplateFindByID :one
SELECT id, source_workflow_id, org_id, title, description, category, clone_count, created_at FROM templates WHERE id = $1
`
