// Code generated by yongol. DO NOT EDIT.
// Sensitive-field log masking for sqlc row: User

//ff:func feature=db type=util control=sequence topic=observability
//ff:what User.LogValue — sensitive 컬럼 [REDACTED] 마스킹 slog.Value 반환
//ff:checked llm=yongol-gen hash=ff250d3f
package db

import (
	"log/slog"
)

// LogValue masks sensitive columns when this row is logged via slog.
// slog.LogValuer is invoked automatically by slog handlers, so ad-hoc calls
// like slog.Info("user", "u", user) never emit the raw sensitive value.
func (r User) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", r.ID),
		slog.Any("org_id", r.OrgID),
		slog.Any("email", r.Email),
		slog.String("password_hash", "[REDACTED]"),
		slog.Any("role", r.Role),
		slog.Any("created_at", r.CreatedAt),
	)
}
