// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

//ff:func feature=db type=model control=sequence
//ff:what userCreate
package db

const userCreate = `-- name: UserCreate :one
INSERT INTO users (org_id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, email, password_hash, role, created_at
`
