// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=model control=sequence
//ff:what webhookListByOrgID
package db

const webhookListByOrgID = `-- name: WebhookListByOrgID :many
SELECT id, org_id, url, event_type, created_at FROM webhooks WHERE org_id = $1 ORDER BY created_at DESC
LIMIT 1000
`
