// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=model control=sequence
//ff:what webhookFindByID
package db

const webhookFindByID = `-- name: WebhookFindByID :one
SELECT id, org_id, url, event_type, created_at FROM webhooks WHERE id = $1
`
