// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:type feature=db type=model
//ff:what WebhookCreateParams
package db

type WebhookCreateParams struct {
	OrgID     int64
	Url       string
	EventType string
}
