// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=model control=sequence
//ff:what webhookDelete
package db

const webhookDelete = `-- name: WebhookDelete :exec
DELETE FROM webhooks WHERE id = $1
`
