// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=model control=sequence
//ff:what webhookListByOrgIDAndEventType
package db

const webhookListByOrgIDAndEventType = `-- name: WebhookListByOrgIDAndEventType :many
SELECT id, org_id, url, event_type, created_at FROM webhooks WHERE org_id = $1 AND event_type = $2
LIMIT 1000
`
