// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:func feature=db type=model control=sequence
//ff:what webhookCreate
package db

const webhookCreate = `-- name: WebhookCreate :one
INSERT INTO webhooks (org_id, url, event_type)
VALUES ($1, $2, $3)
RETURNING id, org_id, url, event_type, created_at
`
