// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

//ff:type feature=db type=model
//ff:what WebhookListByOrgIDAndEventTypeParams
package db

type WebhookListByOrgIDAndEventTypeParams struct {
	OrgID     int64
	EventType string
}
