// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what Webhook
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Webhook struct {
	ID        int64
	OrgID     int64
	Url       string
	EventType string
	CreatedAt pgtype.Timestamptz
}
