// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what workflowCreate
package db

const workflowCreate = `-- name: WorkflowCreate :one
INSERT INTO workflows (org_id, title, trigger_event)
VALUES ($1, $2, $3)
RETURNING id, org_id, title, trigger_event, status, version, root_workflow_id, created_at
`
