// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:type feature=db type=model
//ff:what WorkflowCreateVersionParams
package db

type WorkflowCreateVersionParams struct {
	OrgID          int64
	Title          string
	TriggerEvent   string
	Version        int64
	RootWorkflowID int64
}
