// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:type feature=db type=model
//ff:what WorkflowCreateParams
package db

type WorkflowCreateParams struct {
	OrgID        int64
	Title        string
	TriggerEvent string
}
