// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

//ff:type feature=db type=model
//ff:what Workflow
package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Workflow struct {
	ID             int64
	OrgID          int64
	Title          string
	TriggerEvent   string
	Status         string
	Version        int64
	RootWorkflowID int64
	CreatedAt      pgtype.Timestamptz
}
