// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what workflowListVersions
package db

const workflowListVersions = `-- name: WorkflowListVersions :many
SELECT id, org_id, title, trigger_event, status, version, root_workflow_id, created_at FROM workflows WHERE (root_workflow_id = $1 OR id = $1) AND org_id = $2 ORDER BY version ASC
LIMIT 1000
`
