// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what workflowFindByID
package db

const workflowFindByID = `-- name: WorkflowFindByID :one
SELECT id, org_id, title, trigger_event, status, version, root_workflow_id, created_at FROM workflows WHERE id = $1
`
