// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what workflowCreateVersion
package db

const workflowCreateVersion = `-- name: WorkflowCreateVersion :one
INSERT INTO workflows (org_id, title, trigger_event, version, root_workflow_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, title, trigger_event, status, version, root_workflow_id, created_at
`
