// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:func feature=db type=model control=sequence
//ff:what workflowListByOrgID
package db

const workflowListByOrgID = `-- name: WorkflowListByOrgID :many
SELECT id, org_id, title, trigger_event, status, version, root_workflow_id, created_at FROM workflows WHERE org_id = $1 ORDER BY created_at DESC
LIMIT 1000
`
