// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

//ff:type feature=db type=model
//ff:what WorkflowListVersionsParams
package db

type WorkflowListVersionsParams struct {
	RootID int64
	OrgID  int64
}
