//ff:func feature=gen-nestjs type=generator control=sequence
//ff:what RenderPackageJSON — NestJS package.json 의존성 목록 생성

package scaffold

import (
	"encoding/json"
	"fmt"
)

// RenderPackageJSON produces the package.json content for a NestJS project.
func RenderPackageJSON(projectID string) (string, error) {
	if projectID == "" {
		return "", fmt.Errorf("RenderPackageJSON: empty projectID")
	}
	pkg := PackageJSON{
		Name:        projectID,
		Version:     "0.0.1",
		Description: fmt.Sprintf("%s — generated by yongol", projectID),
		Scripts: map[string]string{
			"build":            "nest build",
			"start":            "nest start",
			"start:dev":        "nest start --watch",
			"start:prod":       "node dist/main",
			"test":             "jest",
			"test:e2e":         "jest --config ./test/jest-e2e.json",
			"prisma:generate":  "prisma generate",
			"prisma:migrate":   "prisma migrate dev",
		},
		Dependencies:    nestDependencies(),
		DevDependencies: nestDevDependencies(),
	}
	data, err := json.MarshalIndent(pkg, "", "  ")
	if err != nil {
		return "", fmt.Errorf("RenderPackageJSON: %w", err)
	}
	return string(data) + "\n", nil
}
