//ff:type feature=migration type=model
//ff:what Migration 패키지 전역 상수 — 경로·파일명·스냅샷 헤더 포맷 정의
package migration

// File / directory layout constants for the DDL migration pipeline.
// These are the contract between Phase001 (design) and Phase002~005
// (implementation). Changing any value here is a breaking change for
// existing projects with committed snapshots / migration files.
const (
	// SnapshotFileName is the baseline snapshot file name. As of Phase010
	// (BUG-034) it lives under <artifacts-dir>/db/ — directly under the
	// db directory, NOT inside db/migrations/. This keeps it out of the
	// scan path of external migration tools (golang-migrate / flyway /
	// goose) that treat db/migrations/ as their sources directory.
	//   <artifacts-dir>/<BaselineSubdir>/<SnapshotFileName>
	// yongol generate reads it at the start of the migration step and
	// overwrites it on success.
	SnapshotFileName = ".latest_schema.sql"

	// DDLSubdir is the sub-path under <specs-dir> that contains the DDL
	// SSOT files (`*.sql`). Baseline snapshots are no longer stored here;
	// see BaselineSubdir for the current baseline location.
	DDLSubdir = "db"

	// SnapshotSubdir is an alias for DDLSubdir kept for source
	// compatibility with callers that still compute DDL directory paths
	// via this name. Prefer DDLSubdir in new code.
	//
	// Deprecated: use DDLSubdir. The baseline no longer lives under
	// <specs-dir>/<SnapshotSubdir>/; see BaselineSubdir.
	SnapshotSubdir = DDLSubdir

	// BaselineSubdir is the sub-path under <artifacts-dir> where the
	// baseline snapshot is written. Phase010 (BUG-034) placed it at
	// <artifacts-dir>/db/ — one level above the migrations/ directory —
	// so external migration tools do not mistake it for a migration.
	BaselineSubdir = "db"

	// MigrationsSubdir is the sub-path under <artifacts-dir> where
	// numbered migration .sql files are emitted.
	MigrationsSubdir = "db/migrations"

	// LegacySnapshotFileName is the pre-Phase010 baseline file name.
	// generate removes any file with this name under <specs-dir>/db/
	// because the baseline now lives in arts/ (see BUG-034).
	LegacySnapshotFileName = ".generated_schema.sql"

	// MigrationFilenameFormat is a Printf format that produces the
	// up migration file name from (sequence int, description string):
	//   fmt.Sprintf(MigrationFilenameFormat, 1, "initial")
	//     => "0001_initial.up.sql"
	// The `.up.sql` suffix matches golang-migrate's expected layout
	// (NNNN_<desc>.up.sql / NNNN_<desc>.down.sql). See Phase007.
	MigrationFilenameFormat = "%04d_%s.up.sql"

	// MigrationDownFilenameFormat is a Printf format that produces the
	// companion stub down migration file name:
	//   fmt.Sprintf(MigrationDownFilenameFormat, 1, "initial")
	//     => "0001_initial.down.sql"
	// yongol emits a no-op stub only — reverse migrations are not
	// auto-generated. See pkg/generate/migration/emit_down_stub.go and
	// docs/MIGRATION.md for the rationale.
	MigrationDownFilenameFormat = "%04d_%s.down.sql"

	// InitialMigrationDesc is the description used for the very first
	// migration emitted when no snapshot exists yet.
	InitialMigrationDesc = "initial"

	// SnapshotHashHeaderPrefix is the first line of a canonical snapshot
	// file. Phase004 MIG-006 verifies this hash to detect user edits.
	// Example: "-- YONGOL_SCHEMA_HASH: 3a7f9c...\n"
	SnapshotHashHeaderPrefix = "-- YONGOL_SCHEMA_HASH: "

	// SnapshotGeneratedHeaderPrefix is the second line of a canonical
	// snapshot — human-readable provenance comment.
	SnapshotGeneratedHeaderPrefix = "-- Generated by yongol "

	// MigrationGeneratedHeaderPrefix is the first line of every emitted
	// migration file.
	MigrationGeneratedHeaderPrefix = "-- Generated by yongol "
)
