//ff:type feature=migration type=model
//ff:what Migration 패키지 전역 상수 — 경로·파일명·스냅샷 헤더 포맷 정의
package migration

// File / directory layout constants for the DDL migration pipeline.
// These are the contract between Phase001 (design) and Phase002~005
// (implementation). Changing any value here is a breaking change for
// existing projects with committed snapshots / migration files.
const (
	// SnapshotFileName is the baseline snapshot stored under <specs>/db/.
	// yongol generate reads it at the start of the migration step and
	// overwrites it on success.
	SnapshotFileName = ".generated_schema.sql"

	// SnapshotSubdir is the sub-path under <specs-dir> that contains DDL
	// files AND the snapshot file. The snapshot lives at
	//   <specs-dir>/<SnapshotSubdir>/<SnapshotFileName>
	SnapshotSubdir = "db"

	// MigrationsSubdir is the sub-path under <artifacts-dir> where
	// numbered migration .sql files are emitted.
	MigrationsSubdir = "db/migrations"

	// MigrationFilenameFormat is a Printf format that produces a
	// migration file name from (sequence int, description string):
	//   fmt.Sprintf(MigrationFilenameFormat, 1, "initial")
	//     => "0001_initial.sql"
	MigrationFilenameFormat = "%04d_%s.sql"

	// InitialMigrationDesc is the description used for the very first
	// migration emitted when no snapshot exists yet.
	InitialMigrationDesc = "initial"

	// SnapshotHashHeaderPrefix is the first line of a canonical snapshot
	// file. Phase004 MIG-006 verifies this hash to detect user edits.
	// Example: "-- YONGOL_SCHEMA_HASH: 3a7f9c...\n"
	SnapshotHashHeaderPrefix = "-- YONGOL_SCHEMA_HASH: "

	// SnapshotGeneratedHeaderPrefix is the second line of a canonical
	// snapshot — human-readable provenance comment.
	SnapshotGeneratedHeaderPrefix = "-- Generated by yongol "

	// MigrationGeneratedHeaderPrefix is the first line of every emitted
	// migration file.
	MigrationGeneratedHeaderPrefix = "-- Generated by yongol "
)
