//ff:func feature=migration type=generator control=sequence
//ff:what RenderDownStub — golang-migrate 호환용 down 파일의 고정 본문 생성
package migration

import (
	"fmt"
	"time"
)

// downStubTemplate is the fixed body of every emitted .down.sql file.
// yongol does not auto-generate reverse migrations — the stub exists
// only so golang-migrate CLI accepts the file layout. See Phase007.
const downStubTemplate = `-- Generated by yongol %s at %s
-- Down stub — intentionally empty.
--
-- yongol does not auto-generate reverse migrations. Roll back by
-- checking out the previous specs/ revision and running
--   yongol generate <specs> <arts>
-- which produces a new forward migration that restores the prior
-- schema. See docs/MIGRATION.md and plans/gen/migration/README.md
-- (v2 scope) for the rationale.
`

// RenderDownStub returns the fixed body of a stub .down.sql file.
// Body is deterministic given (yongolVersion, now) — no ops or schema
// state is inspected. `now` is serialized in RFC3339 UTC.
func RenderDownStub(yongolVersion string, now time.Time) string {
	return fmt.Sprintf(downStubTemplate, yongolVersion, now.UTC().Format(time.RFC3339))
}
