//ff:func feature=migration type=test control=sequence
//ff:what TestEmitCreateTableWithIdentityByDefault — CreateTable.SQL 출력에 GENERATED BY DEFAULT AS IDENTITY 포함
package migration

import (
	"strings"
	"testing"
)

func TestEmitCreateTableWithIdentityByDefault(t *testing.T) {
	tbl := &Table{
		Name: "things",
		Columns: []*Column{
			{
				Name:     "id",
				Type:     CanonicalType{Base: "BIGINT"},
				Nullable: false,
				Identity: &IdentitySpec{Always: false},
			},
		},
		PrimaryKey: []string{"id"},
	}
	op := CreateTable{Table: tbl}
	sql := op.SQL()
	if !strings.Contains(sql, "GENERATED BY DEFAULT AS IDENTITY") {
		t.Errorf("SQL should contain GENERATED BY DEFAULT AS IDENTITY, got:\n%s", sql)
	}
	if strings.Contains(sql, "ALWAYS") {
		t.Errorf("SQL should NOT contain ALWAYS for BY DEFAULT, got:\n%s", sql)
	}
}
