//ff:type feature=migration type=model
//ff:what IdentitySpec — GENERATED [ALWAYS|BY DEFAULT] AS IDENTITY 컬럼 속성
package migration

// IdentitySpec describes a GENERATED AS IDENTITY column attribute.
// Always == true  → GENERATED ALWAYS AS IDENTITY
// Always == false → GENERATED BY DEFAULT AS IDENTITY
type IdentitySpec struct {
	Always bool
}
