//ff:func feature=migration type=test control=iteration dimension=1
//ff:what TestRenderColumn — NOT NULL / IDENTITY / DEFAULT 조합별 컬럼 절 렌더
package migration

import (
	"testing"
)

func TestRenderColumn(t *testing.T) {
	cases := []struct {
		name string
		col  *Column
		want string
	}{
		{"nullable plain", &Column{Name: "a", Type: CanonicalType{Base: "TEXT"}, Nullable: true}, "a TEXT"},
		{"not null", &Column{Name: "a", Type: CanonicalType{Base: "TEXT"}, Nullable: false}, "a TEXT NOT NULL"},
		{"with default", &Column{Name: "n", Type: CanonicalType{Base: "INTEGER"}, Nullable: true, Default: "0"}, "n INTEGER DEFAULT 0"},
		{"identity always", &Column{Name: "id", Type: CanonicalType{Base: "BIGINT"}, Nullable: false, Identity: &IdentitySpec{Always: true}}, "id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY"},
		{"identity by default", &Column{Name: "id", Type: CanonicalType{Base: "BIGINT"}, Nullable: false, Identity: &IdentitySpec{Always: false}}, "id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY"},
	}
	for _, c := range cases {
		c := c
		t.Run(c.name, func(t *testing.T) {
			if got := renderColumn(c.col); got != c.want {
				t.Errorf("renderColumn() = %q, want %q", got, c.want)
			}
		})
	}
}
