//ff:func feature=migration type=test control=iteration dimension=1
//ff:what TestRenderDownStub — stub 본문에 version/timestamp/marker 라인이 포함되는지 확인
package migration

import (
	"strings"
	"testing"
	"time"
)

// TestRenderDownStub verifies the down stub contains the yongol version,
// the UTC timestamp and the explanatory marker lines so downstream
// tooling can parse / recognise yongol-generated stubs.
func TestRenderDownStub(t *testing.T) {
	now := time.Date(2026, 4, 24, 12, 34, 56, 0, time.UTC)
	body := RenderDownStub("v0.2.3", now)

	wantSubstrings := []string{
		"-- Generated by yongol v0.2.3 at 2026-04-24T12:34:56Z",
		"-- Down stub — intentionally empty.",
		"yongol does not auto-generate reverse migrations.",
		"yongol generate <specs> <arts>",
	}
	for _, want := range wantSubstrings {
		if !strings.Contains(body, want) {
			t.Errorf("down stub missing %q. body:\n%s", want, body)
		}
	}
}
