//ff:func feature=migration type=test control=iteration dimension=1
//ff:what EmitSQL — 파일 단위 BEGIN/COMMIT 래핑 + 주석 헤더
package migration

import (
	"strings"
	"testing"
	"time"
)

func TestEmitSQL_Wrapping(t *testing.T) {
	ops := []Operation{
		AddColumn{Table: "users", Column: &Column{
			Name: "email_verified", Type: CanonicalType{Base: "BOOLEAN"},
			Nullable: false, Default: "FALSE",
		}},
	}
	out := EmitSQL(ops, EmitOptions{
		YongolVersion: "v0.1.22",
		GeneratedAt:    time.Date(2026, 4, 22, 15, 30, 0, 0, time.UTC),
	})
	if !strings.Contains(out, "BEGIN;") || !strings.Contains(out, "COMMIT;") {
		t.Errorf("missing BEGIN/COMMIT wrapping:\n%s", out)
	}
	if !strings.Contains(out, "-- Generated by yongol v0.1.22") {
		t.Errorf("missing header: %s", out)
	}
	if !strings.Contains(out, "ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE;") {
		t.Errorf("SQL body wrong:\n%s", out)
	}
}

func TestEmitSQL_Determinism(t *testing.T) {
	ops := []Operation{
		AddColumn{Table: "t", Column: &Column{Name: "c", Type: CanonicalType{Base: "TEXT"}, Nullable: true}},
	}
	ts := time.Date(2026, 4, 22, 15, 30, 0, 0, time.UTC)
	a := EmitSQL(ops, EmitOptions{YongolVersion: "v1", GeneratedAt: ts})
	b := EmitSQL(ops, EmitOptions{YongolVersion: "v1", GeneratedAt: ts})
	if a != b {
		t.Errorf("non-deterministic output:\na=%s\nb=%s", a, b)
	}
}
