//ff:func feature=migration type=util control=sequence
//ff:what WriteSnapshot — canonical SQL + YONGOL_SCHEMA_HASH 헤더로 .generated_schema.sql 갱신
package migration

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// WriteSnapshot renders the Schema as canonical SQL, computes the
// sha256 of that body, and writes:
//
//     -- YONGOL_SCHEMA_HASH: <hex>
//     -- Generated by yongol <version> at <ts>
//     <canonical SQL body>
//
// The hash covers the body *including* the "Generated by" comment
// (second line) so any edit — even cosmetic — invalidates it.
func WriteSnapshot(path string, s *Schema, yongolVersion string, ts time.Time) error {
	if yongolVersion == "" {
		yongolVersion = "vX.Y.Z"
	}
	if ts.IsZero() {
		ts = time.Now().UTC()
	}
	body := fmt.Sprintf("%s%s at %s\n\n%s",
		SnapshotGeneratedHeaderPrefix, yongolVersion, ts.UTC().Format(time.RFC3339),
		CanonicalSQL(s))
	sum := sha256.Sum256([]byte(body))
	head := SnapshotHashHeaderPrefix + hex.EncodeToString(sum[:]) + "\n"
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(head+body), 0644)
}
