// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what AuditLog defines model for AuditLog.
package api

import (
	"time"
)

// AuditLog defines model for AuditLog.
type AuditLog struct {
	Action       *string    `json:"action,omitempty"`
	ActorId      *int64     `json:"actor_id,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	Detail       *string    `json:"detail,omitempty"`
	Id           *int64     `json:"id,omitempty"`
	OrgId        *int64     `json:"org_id,omitempty"`
	ResourceId   *int64     `json:"resource_id,omitempty"`
	ResourceType *string    `json:"resource_type,omitempty"`
}
