// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=model control=sequence
//ff:what BearerAuthScopes
package api

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)
