// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=model control=sequence
//ff:what Defines values for ListAuditLogsParamsSortBy.
package api

// Defines values for ListAuditLogsParamsSortBy.
const (
	ListAuditLogsParamsSortByAction    ListAuditLogsParamsSortBy = "action"
	ListAuditLogsParamsSortByCreatedAt ListAuditLogsParamsSortBy = "created_at"
)

// Defines values for ListAuditLogsParamsSortDir.
const (
	Asc  ListAuditLogsParamsSortDir = "asc"
	Desc ListAuditLogsParamsSortDir = "desc"
)

// Defines values for RegisterJSONBodyRole.
const (
	Admin  RegisterJSONBodyRole = "admin"
	Member RegisterJSONBodyRole = "member"
)
