// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what CreateActionJSONBody defines parameters for CreateAction.
package api

// CreateActionJSONBody defines parameters for CreateAction.
type CreateActionJSONBody struct {
	ActionType    string `json:"action_type"`
	Config        string `json:"config"`
	SequenceOrder int64  `json:"sequence_order"`
}
