// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=sequence
//ff:what CreateWorkflow201JSONResponse.VisitCreateWorkflowResponse
//ff:checked llm=yongol-gen hash=8322c59b
package api

import (
	"encoding/json"
	"net/http"
)

func (response CreateWorkflow201JSONResponse) VisitCreateWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}
