// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what CreateWorkflowJSONBody defines parameters for CreateWorkflow.
package api

// CreateWorkflowJSONBody defines parameters for CreateWorkflow.
type CreateWorkflowJSONBody struct {
	Title        string `json:"title"`
	TriggerEvent string `json:"trigger_event"`
}
