// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=sequence
//ff:what CreateWorkflowVersion201JSONResponse.VisitCreateWorkflowVersionResponse
//ff:checked llm=yongol-gen hash=d5371e22
package api

import (
	"encoding/json"
	"net/http"
)

func (response CreateWorkflowVersion201JSONResponse) VisitCreateWorkflowVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}
