// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what CreateWebhook201JSONResponse
package api

type CreateWebhook201JSONResponse struct {
	Webhook *Webhook `json:"webhook,omitempty"`
}
