// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what ExecuteWorkflow200JSONResponse
package api

type ExecuteWorkflow200JSONResponse struct {
	ExecutionLog *ExecutionLog `json:"execution_log,omitempty"`
}
