// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=sequence
//ff:what ExecuteWorkflow401JSONResponse.VisitExecuteWorkflowResponse
//ff:checked llm=yongol-gen hash=f78374a5
package api

import (
	"encoding/json"
	"net/http"
)

func (response ExecuteWorkflow401JSONResponse) VisitExecuteWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}
