// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what ExecutionLog defines model for ExecutionLog.
package api

import (
	"time"
)

// ExecutionLog defines model for ExecutionLog.
type ExecutionLog struct {
	CreditsSpent *int64     `json:"credits_spent,omitempty"`
	ExecutedAt   *time.Time `json:"executed_at,omitempty"`
	Id           *int64     `json:"id,omitempty"`
	OrgId        *int64     `json:"org_id,omitempty"`
	Status       *string    `json:"status,omitempty"`
	WorkflowId   *int64     `json:"workflow_id,omitempty"`
}
