// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what ListAuditLogsParams defines parameters for ListAuditLogs.
package api

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	Page    *int32                      `form:"page,omitempty" json:"page,omitempty"`
	PerPage *int32                      `form:"per_page,omitempty" json:"per_page,omitempty"`
	SortBy  *ListAuditLogsParamsSortBy  `form:"sort_by,omitempty" json:"sort_by,omitempty"`
	SortDir *ListAuditLogsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	Action  *string                     `form:"action,omitempty" json:"action,omitempty"`
}
