// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=selection
//ff:what Valid indicates whether the value is a known member of the ListAuditLogsParamsSortDir enum.
//ff:checked llm=yongol-gen hash=c49f67d0
package api

// Valid indicates whether the value is a known member of the ListAuditLogsParamsSortDir enum.
func (e ListAuditLogsParamsSortDir) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}
