// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=selection
//ff:what Valid indicates whether the value is a known member of the ListAuditLogsParamsSortBy enum.
//ff:checked llm=yongol-gen hash=981052f6
package api

// Valid indicates whether the value is a known member of the ListAuditLogsParamsSortBy enum.
func (e ListAuditLogsParamsSortBy) Valid() bool {
	switch e {
	case ListAuditLogsParamsSortByAction:
		return true
	case ListAuditLogsParamsSortByCreatedAt:
		return true
	default:
		return false
	}
}
