// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what ListAuditLogsParamsSortBy defines parameters for ListAuditLogs.
package api

// ListAuditLogsParamsSortBy defines parameters for ListAuditLogs.
type ListAuditLogsParamsSortBy string
