// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what ListExecutionLogsResponseObject
package api

import (
	"net/http"
)

type ListExecutionLogsResponseObject interface {
	VisitListExecutionLogsResponse(w http.ResponseWriter) error
}
