// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=sequence
//ff:what ListActions500JSONResponse.VisitListActionsResponse
//ff:checked llm=yongol-gen hash=fe3c396f
package api

import (
	"encoding/json"
	"net/http"
)

func (response ListActions500JSONResponse) VisitListActionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}
