// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what ListTemplatesParams defines parameters for ListTemplates.
package api

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	Cursor   *int64  `form:"cursor,omitempty" json:"cursor,omitempty"`
	PerPage  *int32  `form:"per_page,omitempty" json:"per_page,omitempty"`
	Category *string `form:"category,omitempty" json:"category,omitempty"`
}
