// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=sequence
//ff:what PauseWorkflow409JSONResponse.VisitPauseWorkflowResponse
//ff:checked llm=yongol-gen hash=946bb6ab
package api

import (
	"encoding/json"
	"net/http"
)

func (response PauseWorkflow409JSONResponse) VisitPauseWorkflowResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}
