// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what PublishTemplateJSONBody defines parameters for PublishTemplate.
package api

// PublishTemplateJSONBody defines parameters for PublishTemplate.
type PublishTemplateJSONBody struct {
	Category         string `json:"category"`
	Description      string `json:"description"`
	SourceWorkflowId int64  `json:"source_workflow_id"`
	Title            string `json:"title"`
}
