// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=sequence
//ff:what RegisterHandlersWithOptions creates http.Handler with additional options
//ff:checked llm=yongol-gen hash=9aab0dcb
package api

import (
	"github.com/gin-gonic/gin"
)

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/audit-logs", wrapper.ListAuditLogs)
	router.GET(options.BaseURL+"/api/dashboard", wrapper.GetDashboard)
	router.GET(options.BaseURL+"/api/templates", wrapper.ListTemplates)
	router.POST(options.BaseURL+"/api/templates", wrapper.PublishTemplate)
	router.GET(options.BaseURL+"/api/templates/:id", wrapper.GetTemplate)
	router.POST(options.BaseURL+"/api/templates/:id/clone", wrapper.CloneTemplate)
	router.GET(options.BaseURL+"/api/webhooks", wrapper.ListWebhooks)
	router.POST(options.BaseURL+"/api/webhooks", wrapper.CreateWebhook)
	router.DELETE(options.BaseURL+"/api/webhooks/:id", wrapper.DeleteWebhook)
	router.GET(options.BaseURL+"/api/workflows", wrapper.ListWorkflows)
	router.POST(options.BaseURL+"/api/workflows", wrapper.CreateWorkflow)
	router.GET(options.BaseURL+"/api/workflows/:id", wrapper.GetWorkflow)
	router.GET(options.BaseURL+"/api/workflows/:id/actions", wrapper.ListActions)
	router.POST(options.BaseURL+"/api/workflows/:id/actions", wrapper.CreateAction)
	router.POST(options.BaseURL+"/api/workflows/:id/activate", wrapper.ActivateWorkflow)
	router.POST(options.BaseURL+"/api/workflows/:id/archive", wrapper.ArchiveWorkflow)
	router.POST(options.BaseURL+"/api/workflows/:id/execute", wrapper.ExecuteWorkflow)
	router.GET(options.BaseURL+"/api/workflows/:id/logs", wrapper.ListExecutionLogs)
	router.POST(options.BaseURL+"/api/workflows/:id/new-version", wrapper.CreateWorkflowVersion)
	router.POST(options.BaseURL+"/api/workflows/:id/pause", wrapper.PauseWorkflow)
	router.GET(options.BaseURL+"/api/workflows/:id/versions", wrapper.ListWorkflowVersions)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
}
