// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=selection
//ff:what Valid indicates whether the value is a known member of the RegisterJSONBodyRole enum.
//ff:checked llm=yongol-gen hash=920444f9
package api

// Valid indicates whether the value is a known member of the RegisterJSONBodyRole enum.
func (e RegisterJSONBodyRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Member:
		return true
	default:
		return false
	}
}
