// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what RegisterJSONBodyRole defines parameters for Register.
package api

// RegisterJSONBodyRole defines parameters for Register.
type RegisterJSONBodyRole string
