// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what RegisterJSONBody defines parameters for Register.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Email    openapi_types.Email  `json:"email"`
	OrgId    int64                `json:"org_id"`
	Password string               `json:"password"`
	Role     RegisterJSONBodyRole `json:"role"`
}
