// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what ServerInterface represents all server handlers.
package api

import (
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List audit logs with pagination
	// (GET /api/audit-logs)
	ListAuditLogs(c *gin.Context, params ListAuditLogsParams)
	// Get org dashboard summary
	// (GET /api/dashboard)
	GetDashboard(c *gin.Context)
	// List templates (cursor pagination)
	// (GET /api/templates)
	ListTemplates(c *gin.Context, params ListTemplatesParams)
	// Publish a workflow as a template
	// (POST /api/templates)
	PublishTemplate(c *gin.Context)
	// Get template detail
	// (GET /api/templates/{id})
	GetTemplate(c *gin.Context, id int64)
	// Clone a template into caller's org
	// (POST /api/templates/{id}/clone)
	CloneTemplate(c *gin.Context, id int64)
	// List org webhooks
	// (GET /api/webhooks)
	ListWebhooks(c *gin.Context)
	// Register a webhook URL
	// (POST /api/webhooks)
	CreateWebhook(c *gin.Context)
	// Delete a webhook
	// (DELETE /api/webhooks/{id})
	DeleteWebhook(c *gin.Context, id int64)
	// List workflows for the current user's org
	// (GET /api/workflows)
	ListWorkflows(c *gin.Context)
	// Create a workflow
	// (POST /api/workflows)
	CreateWorkflow(c *gin.Context)
	// Get a workflow by ID
	// (GET /api/workflows/{id})
	GetWorkflow(c *gin.Context, id int64)
	// List actions for a workflow
	// (GET /api/workflows/{id}/actions)
	ListActions(c *gin.Context, id int64)
	// Create an action for a workflow
	// (POST /api/workflows/{id}/actions)
	CreateAction(c *gin.Context, id int64)
	// Activate a workflow
	// (POST /api/workflows/{id}/activate)
	ActivateWorkflow(c *gin.Context, id int64)
	// Archive a workflow
	// (POST /api/workflows/{id}/archive)
	ArchiveWorkflow(c *gin.Context, id int64)
	// Execute a workflow
	// (POST /api/workflows/{id}/execute)
	ExecuteWorkflow(c *gin.Context, id int64)
	// List execution logs for a workflow
	// (GET /api/workflows/{id}/logs)
	ListExecutionLogs(c *gin.Context, id int64)
	// Clone workflow into a new draft version
	// (POST /api/workflows/{id}/new-version)
	CreateWorkflowVersion(c *gin.Context, id int64)
	// Pause a workflow
	// (POST /api/workflows/{id}/pause)
	PauseWorkflow(c *gin.Context, id int64)
	// List all versions of a workflow
	// (GET /api/workflows/{id}/versions)
	ListWorkflowVersions(c *gin.Context, id int64)
	// Login
	// (POST /auth/login)
	Login(c *gin.Context)
	// Register a new user
	// (POST /auth/register)
	Register(c *gin.Context)
}
