// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what CreateWebhook operation middleware
//ff:checked llm=yongol-gen hash=69fa1789
package api

import (
	"github.com/gin-gonic/gin"
)

// CreateWebhook operation middleware
func (siw *ServerInterfaceWrapper) CreateWebhook(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateWebhook(c)
}
