// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what ListActions operation middleware
//ff:checked llm=yongol-gen hash=0dc50d12
package api

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

// ListActions operation middleware
func (sh *strictHandler) ListActions(ctx *gin.Context, id int64) {
	var request ListActionsRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListActions(ctx, request.(ListActionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListActions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListActionsResponseObject); ok {
		if err := validResponse.VisitListActionsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
