// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what StrictServerInterface represents all server handlers.
package api

import (
	"context"
)

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List audit logs with pagination
	// (GET /api/audit-logs)
	ListAuditLogs(ctx context.Context, request ListAuditLogsRequestObject) (ListAuditLogsResponseObject, error)
	// Get org dashboard summary
	// (GET /api/dashboard)
	GetDashboard(ctx context.Context, request GetDashboardRequestObject) (GetDashboardResponseObject, error)
	// List templates (cursor pagination)
	// (GET /api/templates)
	ListTemplates(ctx context.Context, request ListTemplatesRequestObject) (ListTemplatesResponseObject, error)
	// Publish a workflow as a template
	// (POST /api/templates)
	PublishTemplate(ctx context.Context, request PublishTemplateRequestObject) (PublishTemplateResponseObject, error)
	// Get template detail
	// (GET /api/templates/{id})
	GetTemplate(ctx context.Context, request GetTemplateRequestObject) (GetTemplateResponseObject, error)
	// Clone a template into caller's org
	// (POST /api/templates/{id}/clone)
	CloneTemplate(ctx context.Context, request CloneTemplateRequestObject) (CloneTemplateResponseObject, error)
	// List org webhooks
	// (GET /api/webhooks)
	ListWebhooks(ctx context.Context, request ListWebhooksRequestObject) (ListWebhooksResponseObject, error)
	// Register a webhook URL
	// (POST /api/webhooks)
	CreateWebhook(ctx context.Context, request CreateWebhookRequestObject) (CreateWebhookResponseObject, error)
	// Delete a webhook
	// (DELETE /api/webhooks/{id})
	DeleteWebhook(ctx context.Context, request DeleteWebhookRequestObject) (DeleteWebhookResponseObject, error)
	// List workflows for the current user's org
	// (GET /api/workflows)
	ListWorkflows(ctx context.Context, request ListWorkflowsRequestObject) (ListWorkflowsResponseObject, error)
	// Create a workflow
	// (POST /api/workflows)
	CreateWorkflow(ctx context.Context, request CreateWorkflowRequestObject) (CreateWorkflowResponseObject, error)
	// Get a workflow by ID
	// (GET /api/workflows/{id})
	GetWorkflow(ctx context.Context, request GetWorkflowRequestObject) (GetWorkflowResponseObject, error)
	// List actions for a workflow
	// (GET /api/workflows/{id}/actions)
	ListActions(ctx context.Context, request ListActionsRequestObject) (ListActionsResponseObject, error)
	// Create an action for a workflow
	// (POST /api/workflows/{id}/actions)
	CreateAction(ctx context.Context, request CreateActionRequestObject) (CreateActionResponseObject, error)
	// Activate a workflow
	// (POST /api/workflows/{id}/activate)
	ActivateWorkflow(ctx context.Context, request ActivateWorkflowRequestObject) (ActivateWorkflowResponseObject, error)
	// Archive a workflow
	// (POST /api/workflows/{id}/archive)
	ArchiveWorkflow(ctx context.Context, request ArchiveWorkflowRequestObject) (ArchiveWorkflowResponseObject, error)
	// Execute a workflow
	// (POST /api/workflows/{id}/execute)
	ExecuteWorkflow(ctx context.Context, request ExecuteWorkflowRequestObject) (ExecuteWorkflowResponseObject, error)
	// List execution logs for a workflow
	// (GET /api/workflows/{id}/logs)
	ListExecutionLogs(ctx context.Context, request ListExecutionLogsRequestObject) (ListExecutionLogsResponseObject, error)
	// Clone workflow into a new draft version
	// (POST /api/workflows/{id}/new-version)
	CreateWorkflowVersion(ctx context.Context, request CreateWorkflowVersionRequestObject) (CreateWorkflowVersionResponseObject, error)
	// Pause a workflow
	// (POST /api/workflows/{id}/pause)
	PauseWorkflow(ctx context.Context, request PauseWorkflowRequestObject) (PauseWorkflowResponseObject, error)
	// List all versions of a workflow
	// (GET /api/workflows/{id}/versions)
	ListWorkflowVersions(ctx context.Context, request ListWorkflowVersionsRequestObject) (ListWorkflowVersionsResponseObject, error)
	// Login
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Register a new user
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
}
