// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what PublishTemplate operation middleware
//ff:checked llm=yongol-gen hash=7a5c2bdb
package api

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

// PublishTemplate operation middleware
func (sh *strictHandler) PublishTemplate(ctx *gin.Context) {
	var request PublishTemplateRequestObject

	var body PublishTemplateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PublishTemplate(ctx, request.(PublishTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PublishTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PublishTemplateResponseObject); ok {
		if err := validResponse.VisitPublishTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
