// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what ListAuditLogs operation middleware
//ff:checked llm=yongol-gen hash=cecd7514
package api

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

// ListAuditLogs operation middleware
func (sh *strictHandler) ListAuditLogs(ctx *gin.Context, params ListAuditLogsParams) {
	var request ListAuditLogsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListAuditLogs(ctx, request.(ListAuditLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAuditLogs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListAuditLogsResponseObject); ok {
		if err := validResponse.VisitListAuditLogsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
