// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what CreateAction operation middleware
//ff:checked llm=yongol-gen hash=77144c6d
package api

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

// CreateAction operation middleware
func (sh *strictHandler) CreateAction(ctx *gin.Context, id int64) {
	var request CreateActionRequestObject

	request.Id = id

	var body CreateActionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAction(ctx, request.(CreateActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAction")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateActionResponseObject); ok {
		if err := validResponse.VisitCreateActionResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
