// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what GetDashboard operation middleware
//ff:checked llm=yongol-gen hash=321708e8
package api

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

// GetDashboard operation middleware
func (sh *strictHandler) GetDashboard(ctx *gin.Context) {
	var request GetDashboardRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDashboard(ctx, request.(GetDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDashboard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetDashboardResponseObject); ok {
		if err := validResponse.VisitGetDashboardResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
