// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what ListTemplates operation middleware
//ff:checked llm=yongol-gen hash=fe1f0b26
package api

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

// ListTemplates operation middleware
func (sh *strictHandler) ListTemplates(ctx *gin.Context, params ListTemplatesParams) {
	var request ListTemplatesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTemplates(ctx, request.(ListTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTemplates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListTemplatesResponseObject); ok {
		if err := validResponse.VisitListTemplatesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
