// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:func feature=api type=handler control=iteration dimension=1
//ff:what CreateWorkflowVersion operation middleware
//ff:checked llm=yongol-gen hash=6bee3f6e
package api

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"net/http"
)

// CreateWorkflowVersion operation middleware
func (sh *strictHandler) CreateWorkflowVersion(ctx *gin.Context, id int64) {
	var request CreateWorkflowVersionRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWorkflowVersion(ctx, request.(CreateWorkflowVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWorkflowVersion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateWorkflowVersionResponseObject); ok {
		if err := validResponse.VisitCreateWorkflowVersionResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
