// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what Template defines model for Template.
package api

import (
	"time"
)

// Template defines model for Template.
type Template struct {
	Category         *string    `json:"category,omitempty"`
	CloneCount       *int64     `json:"clone_count,omitempty"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	Description      *string    `json:"description,omitempty"`
	Id               *int64     `json:"id,omitempty"`
	OrgId            *int64     `json:"org_id,omitempty"`
	SourceWorkflowId *int64     `json:"source_workflow_id,omitempty"`
	Title            *string    `json:"title,omitempty"`
}
