// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what Webhook defines model for Webhook.
package api

import (
	"time"
)

// Webhook defines model for Webhook.
type Webhook struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	EventType *string    `json:"event_type,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	OrgId     *int64     `json:"org_id,omitempty"`
	Url       *string    `json:"url,omitempty"`
}
