// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.

//ff:type feature=api type=model
//ff:what Workflow defines model for Workflow.
package api

import (
	"time"
)

// Workflow defines model for Workflow.
type Workflow struct {
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Id             *int64     `json:"id,omitempty"`
	OrgId          *int64     `json:"org_id,omitempty"`
	RootWorkflowId *int64     `json:"root_workflow_id,omitempty"`
	Status         *string    `json:"status,omitempty"`
	Title          *string    `json:"title,omitempty"`
	TriggerEvent   *string    `json:"trigger_event,omitempty"`
	Version        *int64     `json:"version,omitempty"`
}
