//ff:func feature=contract type=util control=iteration dimension=1
//ff:what StripAnnotationBlock — 파일 상단의 //ff: 어노테이션 블록과 선행 generator 배너를 제거

package contract

import (
	"bytes"
	"strings"
)

// StripAnnotationBlock removes the filefunc annotation block (and any
// leading "Code generated by ... DO NOT EDIT." banner / build tag
// comments that precede it) from the top of src and returns the body
// that follows. The returned slice begins at the first non-annotation,
// non-banner line (typically the "package <name>" line).
//
// The rules:
//
//   - the scan walks whole lines (split on "\n"); empty lines and any
//     line starting with "//" (after optional leading whitespace) are
//     considered part of the header and discarded until the first
//     non-comment line
//   - once the first line that is neither blank nor "//…" is seen,
//     everything from that line onward is returned unchanged
//
// StripAnnotationBlock intentionally discards the `//ff:checked` line
// along with the rest of the header so that ComputeBodyHash produces a
// stable value regardless of whether the hash line is present.
//
// The input should already have been passed through NormalizeBody so
// callers only have to deal with "\n" separators.
func StripAnnotationBlock(src []byte) []byte {
	if len(src) == 0 {
		return src
	}
	idx := 0
	for idx < len(src) {
		nl := bytes.IndexByte(src[idx:], '\n')
		var line []byte
		var next int
		if nl < 0 {
			line = src[idx:]
			next = len(src)
		} else {
			line = src[idx : idx+nl]
			next = idx + nl + 1
		}
		trim := strings.TrimSpace(string(line))
		if trim == "" || strings.HasPrefix(trim, "//") {
			idx = next
			continue
		}
		break
	}
	return src[idx:]
}
